### ISSUE TITLE
Error when opening Nvim: Error detected while processing FileType Autocommands for "*":

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-treesitter/nvim-treesitter#1083]
I am getting this error when trying to opening Nvim:

![2021-03-22_13-28](https://user-images.githubusercontent.com/17055027/112024149-a93dbd80-8b12-11eb-8981-e5b8307745e9.png)

I know about the existance of this issue [here](https://github.com/nvim-treesitter/nvim-tree-docs/issues/3)
But is not the same thing, nor the workarounds quoted there works for me. And it is a treesitter problem, if i disable the plugin, my Nvim opens normally.

**Comment by theHamsta** [comment]
Please have a look at the three most recently closed issues: https://github.com/nvim-treesitter/nvim-treesitter/issues?q=is%3Aissue+is%3Aclosed

In essence: you need a newer version of Nightly nvim because it will be built with a newer tree-sitter runtime. When you are building nvim yourself, try to do a `make clean` to not hit #1022 (also CMake might not download a more recent version of tree-sitter automatically. so try to clean all kind of build caches)

**Comment by hrqmonteiro** [comment]
If i install any version of Nvim newer than the [#13875](https://github.com/neovim/neovim/pull/13875) commit, it simply breaks my config.

It keeps saying this error: `E5113: Error while calling lua chunk: vim.lua:269: Tried to call API function with vim.fn: use vim.api.nvim_set_keymap instead` if i try to open.

And if i replace all of my `vim.fn` lines, it simply doesn't work either.
