### ISSUE TITLE
Context parsing for styled components in jsx/tsx

### ISSUE THREAD

**Issue by timsofteng** [nvim-treesitter/nvim-treesitter#1111]
**Is your feature request related to a problem? Please describe.**
Tresitter doesn't recognize `styled` comonents in .tsx files. I'm not sure how it could be implemented unfortunately. Take a look at screenshot.
![image](https://user-images.githubusercontent.com/51912173/112873324-272d3600-90ca-11eb-9ef6-7b8b7a15a07c.png)

**Describe the solution you'd like**
Treesitter shoud parse styled component and highlight its content as css or something like that.

**Comment by vigoux** [comment]
That's done by language injection, so the "only" thing to do is to :
- determine what node correspond to the `styled` thing
- use that to enable a `css` injection in the following text

**Comment by elianiva** [comment]
and someone needs to make a proper css-in-js parser, unless you're OK with this broken-ish highlighting because css property isn't supposed to go outside of the curly braces and it will get worse once you introduce a bit more complex JS expression. There's a discussion about this on Zulip iirc.

![image](https://user-images.githubusercontent.com/51877647/112913280-8a978200-9123-11eb-90f4-c97ec746da73.png)

**Comment by steelsojka** [comment]
We should be able to just extend the css parser with a node for `${}` interpolation. Then we can use an injection directive to use the the parent trees language... that way this would work out of the box with TS or JS.

**Comment by marcelarie** [comment]
Hey!! Any news on this? I will love to know how to do this manually if not. 👍🏽

**Comment by timsofteng** [comment]
I'm tracking this as well.

**Comment by steelsojka** [comment]
I don't think anyone is actively working on a parser that can support this syntax. The current architecture  can support the injections but we need a parser that can support css syntax with JS template strings.

**Comment by UltiRequiem** [comment]
Bump

**Comment by kyazdani42** [comment]
for people wanting this, just add a query in your neovim configuration folder under `after/queries/ecma/injections.scm` with that content:
```scheme
(call_expression
  (member_expression
    (identifier) @_styled
    (#eq? @_styled "styled"))
  (template_string) @css (#offset! @css 0 1 0 -1))
```
It will not be perfect but still you'll have some highlight

**Comment by CallumHoward** [comment]
> It will not be perfect but still you'll have some highlight

This works great, thanks @kyazdani42! I notice it works well for 
```typescript
const StyledH1 = styled.h1`...
``` 

but not so much for 
```typescript
const StyledComponent = styled(Component)`...
```

Is there an easy tweak to have it work on example 2?

**Comment by rudotriton** [comment]
@CallumHoward you could try what's proposed in #1628

**Comment by CallumHoward** [comment]
Amazing, that works great ta.

**Comment by rodamaral** [comment]
With this injection, syntax breaks after an interpolation:

![image](https://user-images.githubusercontent.com/5865149/139592477-cb23e07c-61c8-4f21-ac93-b9bb619faa61.png)

**Comment by elianiva** [comment]
well of course it breaks, it's just css parser.
ideally someone should make an extended css parser with support for Javascript template syntax.

**Comment by theHamsta** [comment]
Shouldn't be to complicated when you extend the original CSS grammar. But it should also be possible to inject CSS in `@combined` mode (when it's fully implemented and exclude the template part (the range is already parsed by the JS parser).

**Comment by Hrle97** [comment]
@theHamsta Does this mean that [this parser](https://github.com/tree-sitter/tree-sitter-css) would have to be modified? I would like to dip my toes into treesitter and I've been annoyed by this problem at work, so I would like to give this problem a shot.

**Comment by theHamsta** [comment]
@Hrle97 yes, you can create your own repo with tree-sitter-css as a npm dependency. You can then overwrite rules of the old grammar like I'm doing for my CUDA parser to extend C++: 

https://github.com/theHamsta/tree-sitter-cuda/blob/master/grammar.js

You should look at which positions in the grammar you can have `${...}` interpolations and then extend those rules to have `${...}` as an alternative to e.g. `44px. But a much cleaner solution would be that we just set the ranges for the CSS parser that are not an interpolation since the JS parser already has parser the gaps in the interpolation string. You would need to do something like this https://github.com/nvim-treesitter/nvim-treesitter/pull/1205. This would work because the CSS parser accepts `width: ;` without errors when we don't feed it with the interpolation range.

We have a similar problem for Rust doc strings which are Markdown but we need to trim away `///`. So it would be nice when someone could move https://github.com/nvim-treesitter/nvim-treesitter/pull/1205 forward but probably also with an alternative where you say what should **not** be included in the injection range.

**Comment by Hrle97** [comment]
Ok, I think I get what the solution is from a high level overview. If I got this right, #1205 fixes a problem where we can't inject a language on multiple (n) nodes within the same match, so once we have that, we can inject javascript inside of `styled-components` template literal strings multiple (n) times which is required for a good solution of this problem. This is also required for Rust doc strings because you want to inject Markdown after each `///` requiring multiple (n) injections for each doc string. @theHamsta is this right or am I missing something?

**Comment by theHamsta** [comment]
`#combined!` won't help you with that as it's originally thought to signalized the `scanner.cc` of the injected language that certain ranges have been skipped (E.g. HTML scanner when injected from the template language https://github.com/tree-sitter/tree-sitter-embedded-template/blob/master/queries/injections-ejs.scm). Nvim has probably misunderstood implementation of `#combined` but it won't help you with that. Injected JS is actually already correctly handled by the parent language. 

We need to handle a different case, just set the CSS ranges but split the range of the whole template string into small subranges between the interpolations. We can easily describe what should be exclude but not what should go inside the injections of CSS. I think Neovim should already handle this correctly, you would just need to add your own directive `#exclude-injection!` (?) that sets those ranges.

```
styled.dev = `{
 display: ${foo}`
}`
```
With a directive that creates two ranges from `{` to `: ` and one for everything after the `${foo}`

But now I realize that a separate parser might be necessary anyway as your example with free-standing `styled.dev = \`display: flex\`` without interpolations wouldn't be valid CSS.

**Comment by Hrle97** [comment]
> `#combined!` won't help you with that as it's originally thought to signalized the `scanner.cc` of the injected language that certain ranges have been skipped (E.g. HTML scanner when injected from the template language https://github.com/tree-sitter/tree-sitter-embedded-template/blob/master/queries/injections-ejs.scm). Nvim has probably misunderstood implementation of #combined but it won't help you with that. Injected JS is actually already correctly handled by the parent language.

I'm sorry if I'm misunderstanding something, but isn't this what we want though?

In example:

```ts
const StyledComponent = styled.div<{ isMobile?: boolean }>`
  display: flex;
  margin: ${({ isMobile }) => isMobile ? '2px' : '4px' };
`;
```

Wouldn't we want to give the CSS parser this:

```css
  display: flex;
  margin: ;
```

, since we already established it handles `margin: ;` properly?

Also, here's a bit more complex example that I took from work:

```tsx
const StickyStyles = styled.div<StyledBoxProps>`
  width: 100%;
  @keyframes slideDown {
    from {transform: translateY(-200%)}
    to {transform: translateY(0)}
  }
  ${({ fixed }) =>
    fixed
      ? css<StyledBoxProps>`
          position: fixed;
          top: ${({ fixedOn }) => `${fixedOn}px`};
          right: 0;
          left: 0;
          z-index: 99;
          box-shadow: ${({ theme }) => theme.shadows[2]};
          transition: all 350ms ease-in-out;
          animation: slideDown 400ms ${({ theme }) => theme.transitions.easing.easeInOut};
        `
      : css<StyledBoxProps>`
          position: relative;
          z-index: 2;
          box-shadow: ${({ theme }) => theme.shadows[1]};
          width: 100%;
        `}
`;
```

For this one with nested injections you would like to give the CSS parser something like this for a start:

```css
  width: 100%;
  @keyframes slideDown {
    from {transform: translateY(-200%)}
    to {transform: translateY(0)}
  }
          position: fixed;
          top: 
          right: 0;
          left: 0;
          z-index: 99;
          box-shadow: ;
          transition: all 350ms ease-in-out;
          animation: slideDown 400ms ;
          position: relative;
          z-index: 2;
          box-shadow: ;
          width: 100%;
```

So,  this seems to be working just fine:

![2022-02-19_19-18](https://user-images.githubusercontent.com/53652902/154813743-a4766aa3-17ba-4252-ba0f-6f616c3be607.png)

On a side note, this should work as well:

```ts
import { createGlobalStyle } from 'styled-components';

export const GlobalStyle = createGlobalStyle`
  @keyframes slideDown {
    from {transform: translateY(-200%)}
    to {transform: translateY(0)}
  }
`;
```

The CSS behind `createGlobalStyle` is not being highlighted at all.

> without interpolations wouldn't be valid CSS.

I know but it works just fine for me (at least for now):

![2022-02-19_18-36](https://user-images.githubusercontent.com/53652902/154812295-682cdb83-33ed-41e6-975b-29264fc141fa.png)

**Comment by theHamsta** [comment]
> Wouldn't we want to give the CSS parser this (just skipping the injected JS):

Yes and no. It would be want we want in the sense that all the no interpolation are in the CSS and that it would be possible to parse it fine. Because of the missing `{` you will have a parser error from which the parser can still somehow recover as you showed in the highlights.

You could try to fix the implementation of `#combined!` here to exclude the children of the injection node from the https://github.com/tree-sitter/tree-sitter/blob/3ff5c19403ccb8e6139a048b3257302a8da6139e/docs/section-4-syntax-highlighting.md#L363-L365 . I'll try to do this tonight this would mitigate our problem here. But reading this docs sounds like our current behavior is `@combined` while we should exclude the interpolation nodes by default.

We initially thought that combined would mean inject every occurrence of this node to one combined document of the child language.
 https://github.com/theHamsta/neovim/blob/3b0a0c6ca6c5f4e719028be2dba11853ffec6b6b/runtime/lua/vim/treesitter/languagetree.lua#L395-L401

the reason why `@combined it's not working right now is https://github.com/neovim/neovim/pull/17099 so `(_)*` queries will only yield the first occurrence of a capture.

**Comment by Hrle97** [comment]
> You could try to fix the implementation of #combined! here to exclude the children of the injection node from the https://github.com/tree-sitter/tree-sitter/blob/3ff5c19403ccb8e6139a048b3257302a8da6139e/docs/section-4-syntax-highlighting.md#L363-L365 . I'll try to do this tonight this would mitigate our problem here. But reading this docs sounds like our current behavior is @combined while we should exclude the interpolation nodes by default.

I was hoping on doing that (or adding `!exclude-injection` as per your last comment) and fixing the CSS injection queries on [this](https://github.com/Hrle97/nvim-treesitter/tree/fix/css-styled-components-highlight) branch (same as `master`, but with #1205 merged) just so I and my peers don't have to read ridiculously highlighted code on monday. I'll try to do that tonight and hopefully use that solution while you're working on getting `combined` working properly because my knowledge of Treesitter is not good enough, but hopefully good enough to fix this roughly. Once I get something working (hopefully), I'll post the code here.

> We initially thought that combined would mean inject every occurrence of this node to one combined document of the child language before tree-sitter had a any documentation of injections
https://github.com/theHamsta/neovim/blob/3b0a0c6ca6c5f4e719028be2dba11853ffec6b6b/runtime/lua/vim/treesitter/languagetree.lua#L395-L401

I'm sorry but I'll have to look into this more and mess around with Treesitter to understand this better.

**Comment by theHamsta** [comment]
@Hrle97 I think our current handling of injections is not inline with what tree-sitter used. I think this should be fixed in https://github.com/neovim/neovim/pull/17099 . With this `@combined` should do it's thing and just always exclude the child nodes of the JS parser.

Did I understand the tree-sitter docs correctly that
- `combined` means CSS is injected but without children of the current node in the JS tree
- `include-children` would be our current behavior to include the JS nodes also for CSS
- `combined` is the default for tree-sitter if nothing is specified

**Comment by Hrle97** [comment]
Ok, I think I have a fix for this for now:

![2022-02-19_22-49](https://user-images.githubusercontent.com/53652902/154820284-d5314a84-6af9-490c-8e04-887a75d76190.png)

The CSS parser is having a hard time with those broken ranges but this is at least better than the solution we had before. I will look at the code again to see if I did something wrong, but if I can't I might try and extend the Treesitter CSS parser tomorrow.

I went with the `!exclude-injection` kind of approach. I made a directive `!ecma_template_literal` that excludes ranges with JS injections in them like this:

```lua
query.add_directive("ecma_template_literal!", function(
  match,
  _, --[[ pattern ]]
  _, --[[ bufnr ]]
  predicate,
  metadata
)
  local node = match[predicate[2]]
  local content = { { node:range() } }

  -- remove backticks
  content[1][2] = content[1][2] + 1
  content[1][4] = content[1][4] - 1

  for child in node:iter_children() do
    -- create subranges
    if child:type() == "template_substitution" then
      local child_range = { child:range() }
      local last_content_range = content[#content]
      local first_part = { last_content_range[1], last_content_range[2], child_range[1], child_range[2] - 1 }
      local second_part = { child_range[3], child_range[4] + 1, last_content_range[3], last_content_range[4] }
      content[#content] = first_part
      content[#content + 1] = second_part
    end
  end

  metadata.content = content
end)
```

Then I added the directive into all ECMA injections like this:

```
; {lang}`<{lang}>`
(call_expression
 function: ((identifier) @language)
 arguments: ((template_string) @content
   (#ecma_template_literal! @content)))

; gql`<graphql>`
(call_expression
 function: ((identifier) @_name
   (#eq? @_name "gql"))
 arguments: ((template_string) @graphql
   (#ecma_template_literal! @graphql)))

; hbs`<glimmer>`
(call_expression
 function: ((identifier) @_name
   (#eq? @_name "hbs"))
 arguments: ((template_string) @glimmer
   (#ecma_template_literal! @glimmer)))

; styled.div`<css>`
(call_expression
 function: (member_expression
   object: (identifier) @_name
     (#eq? @_name "styled"))
 arguments: ((template_string) @css
   (#ecma_template_literal! @css)))

; styled(Component)`<css>`
(call_expression
 function: (call_expression
   function: (identifier) @_name
     (#eq? @_name "styled"))
 arguments: ((template_string) @css
   (#ecma_template_literal! @css)))

; styled.div.attrs({ prop: "foo" })`<css>`
(call_expression
 function: (call_expression
   function: (member_expression
    object: (member_expression
      object: (identifier) @_name
        (#eq? @_name "styled"))))
 arguments: ((template_string) @css
   (#ecma_template_literal! @css)))

; styled(Component).attrs({ prop: "foo" })`<css>`
(call_expression
 function: (call_expression
   function: (member_expression
    object: (call_expression
      function: (identifier) @_name
        (#eq? @_name "styled"))))
 arguments: ((template_string) @css
   (#ecma_template_literal! @css)))

; createGlobalStyle`<css>`
(call_expression
 function: (identifier) @_name
   (#eq? @_name "createGlobalStyle")
 arguments: ((template_string) @css
   (#ecma_template_literal! @css)))
```

Is this good enough for a PR until it gets a more natural solution @theHamsta ?

**Comment by Hrle97** [comment]
Lol I fixed it:

![2022-02-19_23-05](https://user-images.githubusercontent.com/53652902/154820709-801f812b-6ff0-4382-aa85-507185776682.png)

Here's the fixed version of the directive:

```lua
query.add_directive("ecma_template_literal!", function(
  match,
  _, --[[ pattern ]]
  _, --[[ bufnr ]]
  predicate,
  metadata
)
  local node = match[predicate[2]]
  local content = { { node:range() } }

  -- remove backticks
  content[1][2] = content[1][2] + 1
  content[1][4] = content[1][4] - 1

  for child in node:iter_children() do
    -- create subranges
    if child:type() == "template_substitution" then
      local child_range = { child:range() }
      local last_content_range = content[#content]
      local first_part = { last_content_range[1], last_content_range[2], child_range[1], child_range[2] - 1 }
      local second_part = { child_range[3], child_range[4], last_content_range[3], last_content_range[4] }
      content[#content] = first_part
      content[#content + 1] = second_part
    end
  end

  metadata.content = content
end)
```

So, if anyone reading this wants a quick fix for now [here is the fork branch one more time](https://github.com/Hrle97/nvim-treesitter/tree/fix/css-styled-components-highlight).

I will make another branch for this on that fork because I merged #1205 into it thinking that I would need that for this issue.

**Comment by kyazdani42** [comment]
I believe js/ts integration with treesitter could be made a plugin at this point :smile:

**Comment by theHamsta** [comment]
@kyazdani42 We just implement the default behavior of tree-sitter then no custom captures are needed.

**Comment by Hrle97** [comment]
> @kyazdani42 We just implement the default behavior of tree-sitter then no custom captures are needed.

Yeah my solution is obviously a hack just so I don't have to see the weird syntax highlighting on monday. 

> Did I understand the tree-sitter docs correctly that: 
> - combined means CSS is injected but without children of the current node in the JS tree
> - include-children would be our current behavior to include the JS nodes also for CSS
> - combined is the default for tree-sitter if nothing is specified

I still don't understand this enough to tell you anything, but the way that you described `combined` matches what I did to fix this.

Here's the [new branch](https://github.com/Hrle97/nvim-treesitter/tree/fix/css-styled-components-highlight-new) without #1205 merged. @theHamsta should I make a PR or wait until `combined` gets fixed and use this as a temporary solution?

**Comment by theHamsta** [comment]
@Hrle97 yes, you can create a PR. But I would rename your predicate to `#inject-without-children!` and remove the check for `interpolation` and just filter out all named children.

**Comment by Hrle97** [comment]
> @Hrle97 yes, you can create a PR. But I would rename your predicate to #inject-without-children! and remove the check for interpolation and just filter out all named children.

Sounds good.

**Comment by theHamsta** [comment]
I'm still in doubt whether we should better fix this upstream. There are two possibilities:

- "combined" is confusing: we rename it in core and have your directive with a different name (not `#combined`) here in nvim-treesitter
- we try to be less confusing by having "combined" mean the same thing as in upstream tree-sitter. We would upstream some code similar to yours and have it in core Neovim

**Comment by Hrle97** [comment]
> I'm still in doubt whether we should better fix this upstream. There are two possibilities:
> 
> * "combined" is confusing: we rename it in core and have your directive with a different name (not `#combined`) here in nvim-treesitter
> * we try to be less confusing by having "combined" mean the same thing as in upstream tree-sitter. We would upstream some code similar to yours and have it in core Neovim

I agree that `combined` is a bit confusing especially now looking back at yesterday trying to understand these things.

I think that that you were right when you said that the current implementation of injections is not in line with the Treesitter documentation on injections. The current behaviour acts as if there is an `include_children!` directive on all injections. If this gets fixed in Neovim we won't need #2557 and ECMA template literal string injections should work automatically.

**Comment by timsofteng** [comment]
Hello guys.
Any chance to implement this feature?

**Comment by clason** [comment]
PR welcome.

**Comment by Hrle97** [comment]
> Hello guys. Any chance to implement this feature? I've opened this feature more than year ago:)

I made a PR #2557 but the maintainers were unhappy with the implementation because they feel like it is something that needs to be fixed inside Neovim itself and I'm a bit hesitant on doing that because I don't know enough about how Neovim to do that nor do I have the time to investigate right now.

**Comment by timsofteng** [comment]
@theHamsta may you please explain what should be fixed in neovim? If issue is in neovim I could open issue there. I just don't know what should I ask.

**Comment by zakissimo** [comment]
Any updates on the matter ?

**Comment by silicakes** [comment]
> @theHamsta may you please explain what should be fixed in neovim? If issue is in neovim I could open issue there. I just don't know what should I ask.

Same here, anyone knows what needs to be communicated for the people @ neovim?

**Comment by marcelarie** [comment]
> > @theHamsta may you please explain what should be fixed in neovim? If issue is in neovim I could open issue there. I just don't know what should I ask.
> 
> Same here, anyone knows what needs to be communicated for the people @ neovim?

@tjdevries ??

**Comment by theHamsta** [comment]
Please don't spam people! The necessary predicate was merged here https://github.com/theHamsta/nvim-treesitter/blob/dc21a92616ffe9f9d521121f48944aa876336432/lua/nvim-treesitter/query_predicates.lua#L155-L132 This should probably made the default to match upstream tree-sitter behavior. Also aspects of #2557 could be integrated into nvim-treesitter to enable `#exclude-chrildren!` for CSS for this repo. The CSS parser might still have difficulties understanding the gaps in it's ranges, but at least the JS regions will be ignored

**Comment by silicakes** [comment]
> Please don't spam people! The necessary predicate was merged here https://github.com/theHamsta/nvim-treesitter/blob/dc21a92616ffe9f9d521121f48944aa876336432/lua/nvim-treesitter/query_predicates.lua#L155-L132 This should probably made the default to match upstream tree-sitter behavior. Also aspects of #2557 (tests and injection query) could be integrated into nvim-treesitter to enable `#exclude-chrildren!` for CSS for this repo. The CSS parser might still have difficulties understanding the gaps in it's ranges, but at least the JS regions will be ignored

Thanks @theHamsta 
Running `:TSInstall css` did the trick for me.
Here are some screenshots 

[material](https://github.com/marko-cerovac/material.nvim)
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1759539/181904094-4db11f92-5899-44a4-a6b2-f213c23151c7.png">

[Nord](https://github.com/arcticicestudio/nord-vim)
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1759539/181904210-6b1a8c80-91eb-419e-9155-113b15127c21.png">

[Gruvbox material](https://github.com/sainnhe/gruvbox-material)

<img width="637" alt="image" src="https://user-images.githubusercontent.com/1759539/181904284-fadb4ec5-030e-4c49-bb57-dec1b7c9d768.png">

[Tokyonight](https://github.com/folke/tokyonight.nvim)

<img width="622" alt="image" src="https://user-images.githubusercontent.com/1759539/181904381-d8e23e79-aa93-4a26-b0af-f2cad66f9498.png">

**Comment by Hrle97** [comment]
@silicakes try interpolating a lambda with props inside the template and see if the syntax highlighting still works

the things you've shown worked before - the problem was in the lambda interpolations

**Comment by silicakes** [comment]
> @silicakes try interpolating a lambda with props inside the template and see if the syntax highlighting still works
> 
> the things you've shown worked before - the problem was in the lambda interpolations

There you go:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/1759539/181909057-e463b3e0-6d8b-4841-8f1c-2c4f3d0c24f5.png">

<img width="597" alt="image" src="https://user-images.githubusercontent.com/1759539/181909079-721f369e-a64e-4f8f-8576-c9dc7281703a.png">

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1759539/181909089-7fe3282b-0276-4fec-adea-422836a78d29.png">

**Comment by Hrle97** [comment]
@silicakes ok my bad

seems like this issue should be closed then

**Comment by silicakes** [comment]
Just noticed it still doesn't play well with `createGlobalStyle`

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1759539/181913261-122d39ca-4f7e-4e31-a0c1-9e70ff7bc008.png">

**Comment by theHamsta** [comment]
Closing as per @Hrle97 comment. Feel free to report remaining issues separately.

**Comment by thedaviddelta** [comment]
Hello guys!

Sorry for the annoyance. What is the current state? Should it work out of the box now? Or do I have to add @Hrle97 fixes manually? Because I haven't quite understood the current state based on the lasts messages.

For me it doesn't work at all. Whether I use type annotations or embeded lambdas (1) the syntax breaks. And whether using plain simple `styled` tags (2) the syntax highlighting works correctly but LSP/CMP don't recognize the language neither for diagnostics or autocompleting (I don't know whether this last problem is because of TS or not).
![1](https://user-images.githubusercontent.com/6679900/184870326-a206eb65-a65e-4373-8281-e2f916bffc08.png)
![2](https://user-images.githubusercontent.com/6679900/184870652-5f99f293-fa5e-4f23-bb58-cf793f7d65cf.png)

I have correctly installed all the needed TS servers (3). What do I have to do?
![3](https://user-images.githubusercontent.com/6679900/184871041-f599d1dc-5799-48b6-aa33-9666654777f4.png)

Regards, David.

**Comment by Hrle97** [comment]
I managed to separate this into a module until it gets fixed (let me know if it doesn't work because I haven't used `styled` in a while):

```lua
local M = {}

local tbl = {}

function tbl.contains(_tbl, value)
  for _, current in pairs(_tbl) do
    if current == value then
      return true
    end
  end

  return false
end

function M.treesitter()
  local function is_one_line(range)
    return range[1] == range[3]
  end

  local function is_range_empty_or_invalid(range)
    if range[3] < range[1] or (is_one_line(range) and range[4] <= range[2]) then
      return true
    end

    return false
  end

  local function make_subranges_between_children_like(node, predicate)
    local content = { { node:range() } }

    for child in node:iter_children() do
      if predicate(child) then
        local child_range = { child:range() }
        local last_content_range = content[#content]
        local first_part = {
          last_content_range[1],
          last_content_range[2],
          child_range[1],
          child_range[2],
        }
        local second_part = {
          child_range[3],
          child_range[4],
          last_content_range[3],
          last_content_range[4],
        }
        if is_range_empty_or_invalid(first_part) then
          if not is_range_empty_or_invalid(second_part) then
            content[#content] = second_part
          end
        elseif is_range_empty_or_invalid(second_part) then
          content[#content] = first_part
        else
          content[#content] = first_part
          content[#content + 1] = second_part
        end
      end
    end

    return content
  end

  -- TODO: make this silent in a different way because this will never produce
  -- TODO: a different directive on :PackerCompiler
  local directives = vim.treesitter.query.list_directives()
  if not tbl.contains(directives, "inject_without_named_children!") then
    vim.treesitter.query.add_directive(
      "inject_without_named_children!",
      function(
        match,
        _, --[[ pattern ]]
        _, --[[ bufnr ]]
        predicate,
        metadata
      )
        local node = match[predicate[2]]
        metadata.content = make_subranges_between_children_like(
          node,
          function(child)
            return child:named()
          end
        )
      end
    )
  end

  if not tbl.contains(directives, "inject_without_children!") then
    vim.treesitter.query.add_directive("inject_without_children!", function(
      match,
      _, --[[ pattern ]]
      _, --[[ bufnr ]]
      predicate,
      metadata
    )
      local node = match[predicate[2]]
      metadata.content = make_subranges_between_children_like(node, function(_)
        return true
      end)
    end)
  end
end

return M
```

Call `M.treesitter()` on startup

**Comment by thedaviddelta** [comment]
Thank you so much @Hrle97, syntax highlighting is now working properly.
But LSP/CMP integration is still completely missing. I don't know if this is off-topic regarding TS, but do you know what do I have to do for it to work with styled-components?
Currently, I can break a CSS declaration and get no error, or start typing and get no autocomplete.
Regards, David.

**Comment by achambel** [comment]
> Thank you so much @Hrle97, syntax highlighting is now working properly.
> But LSP/CMP integration is still completely missing. I don't know if this is off-topic regarding TS, but do you know what do I have to do for it to work with styled-components?
> Currently, I can break a CSS declaration and get no error, or start typing and get no autocomplete.
> Regards, David.

This plugin worked for me: https://github.com/microsoft/typescript-styled-plugin

**Comment by thedaviddelta** [comment]
Yep, thanks!
I took it a look and was able to get it working by installing it locally in the project and specifying the plugin in the project's `tsconfig.json`!
Unfortunately, I wasn't able to install it globally, or in a neutral folder, and make it work by using the LSP config object as specified on the documentation, just as VSCode does by default. So it would take me to pollute the original project's common files in order to get it to work, something not ideal.
At least something is something. I won't get deeper into this as this is not a LSP issue but a Treesitter one and it's getting a bit out-of-topic, but if someone discovers something more related to `styled-components` setup please mention it.

**Comment by vatosarmat** [comment]
This https://github.com/nvim-treesitter/nvim-treesitter/issues/1111#issuecomment-1216655480 doesn't work on `neovim v0.8` because of this line https://github.com/neovim/neovim/blob/b1ae775de618e3e87954a88d533ec17bbef41cdf/runtime/lua/vim/treesitter/languagetree.lua#L365. The `>= 4` looks like a bug

**Comment by TheAdamBorek** [comment]
Will add a note to others looking for the same problem as I was...

As of today 
```tsx
styled.div``
```
should work out of the box. Just make sure you have added BOTH `css` & `styled` parsers to your Treesitter config. I missed the latter and it took me a while to spot it 🙈
