### ISSUE TITLE
Provide a way to query which highlights are being used at buffer position

### ISSUE THREAD

**Issue by andymass** [nvim-treesitter/nvim-treesitter#1228]
**Is your feature request related to a problem? Please describe.**
Many plugins query the syntax in the buffer to do their work.  When tree-sitter highlighting is enabled, they break because by default syntax is set to "".  Some examples #584 , #1184.  There is "additional_vim_regex_highlighting" which re-enables syntax but that of course comes with a performance penalty.

**Describe the solution you'd like**

Allow querying neovims's tree-sitter highlighting result for the syntax groups being applied to the document. This is similar to synID() but available when using the tree-sitter provider.  

A function which returns the active highlight group(s) for a given (line, column).

**Describe alternatives you've considered**

I considered running my own highlight queries, but this will be less efficient.  I also considered hacking neovim's highlighter.lua module but having a standard utility function would be better.

Fully "harmonize" the old and new syntax engines somehow.  E.g., synId() would work.  This is more of a core neovim option.

**Comment by theHamsta** [comment]
`:TSHighlightsUnderCursor`
https://github.com/nvim-treesitter/playground

You could factor out the code to an actual function instead of a display of a floating window.

Plugins should not rely on the syntax highlighting but do their own tree-sitter queries.

**Comment by andymass** [comment]
@theHamsta, that's a fair point, and thanks..  Actually, in my testing `:TSHighlightsUnderCursor` doesn't work correctly in the sense that its results differ from the highlighting actually being applied via buf highlights, which is a reason I opened this (though I can probably open such an issue to playground repo if this is unexpected).

The prime use-case I have in mind is comments and strings.  My logic here was merely if the highlighting query is *already* being done, and a plugin simply needs to know what syntax is under the cursor, that it's computationally wasteful to run another query.  Though perhaps the cost of a iterating through a query is not actually that high..

**Comment by theHamsta** [comment]
:TSHighlightsUnderCursor are the captures that are supposed to be applied. I suppose https://github.com/neovim/neovim/pull/14245 breaks this and sometimes applies highlight groups by caching previous values of hl_map which it shouldn't. The true values are stored in a per-language `hl_cache`. :TSHighlightsUnderCursor does also not show that at the moment pythonTSParameter is supposed to be used instead of `TSParameter`. I say supposed because I'm not sure if that's the case right now: https://github.com/neovim/neovim/pull/14245#issuecomment-824733188

It predates the current highlighting :TSHighlightsUnderCursor and is probably a bit outdated. You could either ask for Nvim to expose this functionality in their module or try to get the highlight groups from the extmarks. The information from the queries is lost because there is not really a point to safe the results after highlighting is done.

**Comment by nullchilly** [comment]
Does https://github.com/neovim/neovim/pull/21393 close this issue?

**Comment by clason** [comment]
Yes, it does.

**Comment by Flimm** [comment]
> Does [neovim/neovim#21393](https://github.com/neovim/neovim/pull/21393) close this issue?

Thank you! `:Inspect` and `:InspectTree` are very helpful.
