### ISSUE TITLE
TSKeywordReturn feature request

### ISSUE THREAD

**Issue by antonk52** [nvim-treesitter/nvim-treesitter#1485]
**Is your feature request related to a problem? Please describe.**
When porting a colorscheme to treesitter I came across a difficulty that treesitter does not expose a highlighting group for the `return` keyword. Which makes it currently impossible to color it differently to other keywords. Though there are highlighting groups for `function` keyword and `operator` keyword [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/4eb19c9e6da5c1628a5e2b4445595ecb39019efc/lua/nvim-treesitter/highlight.lua#L46-L48). The return keyword is pretty popular for C syntax like languages.

**Describe the solution you'd like**
It would be useful to be able to have `TSKeyword.Return` as its own color highlighting group as it could be used in 

**Describe alternatives you've considered**
Inapplicable.

**Additional context**
Here is a sample of highlighting for the same theme (base16-ocean). The above one is using the default regexp based highlighting and the below one is using treesitter. As can be seen the return keyword is a different color.

<img width="714" alt="Screen Shot 2021-07-04 at 17 38 02" src="https://user-images.githubusercontent.com/5817809/124389171-a72cf280-dcee-11eb-8479-5acdc6d575bf.png">

**Comment by theHamsta** [comment]
I would be very open to this suggestion for return/yield keywords. Do you want to create a PR to introduce this feature? Just ping me in case you need any help!

**Comment by antonk52** [comment]
Happy to help implement this though I am not familiar with the codebase. From my current understanding in this repository only the keywords themselves should added about [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/4eb19c9e6da5c1628a5e2b4445595ecb39019efc/lua/nvim-treesitter/highlight.lua#L46-L48) and then they should get supported in the parser plugins. Is this assumption correct?

**Comment by theHamsta** [comment]
You would need to
- add a highlight group here https://github.com/nvim-treesitter/nvim-treesitter/blob/b3aac12f59fc5af1add18ae5ab2555b2e0d4e8e0/plugin/nvim-treesitter.vim#L64 Choose a default Vim highlight group. In doubt just `TSKeyword` since this was the highlight before
- add capture `@keyword.return` here https://github.com/nvim-treesitter/nvim-treesitter/blob/4eb19c9e6da5c1628a5e2b4445595ecb39019efc/lua/nvim-treesitter/highlight.lua#L46-L48
- search for all the occurrences of `"return"`/`"yield"` in `queries/*/highlight.scm`. They should be `@keyword` now. Change them to the new `@keyword.return`

**Comment by antonk52** [comment]
Thank you for the detailed explanation I will try to send a PR later on tonight

**Comment by theHamsta** [comment]
And I forgot: adding TSkeywordReturn to documentation and CONTRIBUTING.md
