### ISSUE TITLE
Highlight breaks vim indentation in Ruby

### ISSUE THREAD

**Issue by brandoncc** [nvim-treesitter/nvim-treesitter#1501]
My `TSModuleInfo` output:

```
>> default       autopairs  highlight  incremental_selection  indent  
ruby             ✓          ✓          ✗                      ✗       
```
The [first indentation issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1500) I experienced was with the indent module, and after I disabled that I experienced another bug:

```ruby
def broken
  puts "a: #{a}"
    puts "b: #{b}" # should not be indented
end

def works
  puts "a"
  puts "b"
end
```

If I disable the `highlight` module, this new bug goes away. Is this a bug, or misconfiguration?

**Comment by brandoncc** [comment]
You are right, that does fix the issue! I'm trying to figure out the right path here...is the only downside to having both on at the same time a speed loss? Would it cause other bugs? Is there a different recommended path? I'm thinking I should probably just leave highlight off for ruby files, but want to understand the repercussions of my decision. Is the only improvement brought by treesitter improved coloring since it can tell types of tokens that vim regex can't?

Thanks for your time.

**Comment by theHamsta** [comment]
I guess the only downside is speed-loss which you won't notice when you vim-regex was fast enough. Also you would see the vim-regex highlights if tree-sitter does not set a highlight in a specific situation.

I'm closing this since we have issues with the same problem already open. In the end, we will have to replace every feature that is implemented with the traditional highlights but tree-sitter is still in a early phase.

**Comment by brandoncc** [comment]
Thanks again for your time, I will play with that setting.
