### ISSUE TITLE
Wrong highlight for javascript/typescript string template

### ISSUE THREAD

**Issue by thaiducdung255** [nvim-treesitter/nvim-treesitter#1848]
After I update the plugin, the variables in javascript/typescript string template are not highlighted.
I tried to add highlights.scm to highlight it but it not working, please help me to fix this, thanks

Here is my treesitter config:
```
require'nvim-treesitter.configs'.setup {
   ensure_installed = false,
   ignore_install   = true,
   highlight = {
      enable = true,
   },
   indent = {
      enable = {
         'javascriptreact'
      }
   },
   autotag = {
      enable = true
   },
   rainbow = {
      enable         = true,
      extended_mode  = true,
      max_file_lines = 1000,
   }
}
```
Here is the screenshot: 
![image](https://user-images.githubusercontent.com/43328993/134099110-1443c432-3733-4bcc-b8f8-bea1ef0b2db6.png)

**Comment by thaiducdung255** [comment]
after diving into the plugin source code, i found this can help the variables to be highlighted again:
In your vim/nvim config directory, create a file after/queries/{file-type}/highlights.scm (file-type: javascript/typescript) and add these lines:
```
((template_substitution) @operator
 (#set! "priority" 105))

((template_substitution (identifier) @variable)
 (#set! "priority" 105))

```

**Comment by thaiducdung255** [comment]
screenshot (after create highlights.scm file):
![image](https://user-images.githubusercontent.com/43328993/134329792-c1976dd7-0d7a-4f14-9c71-9239bfbf4570.png)

**Comment by stsewd** [comment]
I think we should fix this, we changed the priority of the interpolation https://github.com/nvim-treesitter/nvim-treesitter/blob/6b3f9087514af0b12a1abc92d5c9f0229e96cc39/queries/ecma/highlights.scm#L182 to fix https://github.com/nvim-treesitter/nvim-treesitter/issues/1688. I think we could solve this similarly or with another query.

**Comment by thaiducdung255** [comment]
thank you very much

**Comment by kyazdani42** [comment]
@stsewd the priority query is actually invalid, it's not a fix since it just disables the highlighting inside the template substitution.
Try a simple
```js
const str = `some string ${withJavascriptCode()}`;
```
`@none` overrides completely all highlighting, which is not supposed to happen.
removing `@none` from the query actually fixes the template string brackets being highlighted with the expected group. 

This issue that was attempted to be solved is actually much harder to fix properly, because it would require setting priority on each javascript group higher than the html groups i believe.
