### ISSUE TITLE
:TSInstall is installing nothing

### ISSUE THREAD

**Issue by jordisantamaria** [nvim-treesitter/nvim-treesitter#1967]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When I run :TSInstall typescript, It says typescript had been installed, but when I run :TSInstallInfo, the only module installed is C, It's not installing any other module.

### To Reproduce

Run :TSInstall typescript
Check If Installed with :TSInstallInfo

### Expected behavior

I expect to be able to install modules, currently I only can install C module.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.0.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+5ad15c9
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por root@jordi

Features: +acl +iconv +tui
See ":help feature-compile"

     archivo "vimrc" del sistema: "$VIM/sysinit.vim"
            predefinido para $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Is nvim-treesitter in your runtime path? Can you check whether there are files in `nvim-treesitter/parser` ?

**Comment by jordisantamaria** [comment]
There isn't files in nvim-treesitter/parser, folder is empty. What do you mean If nvim-treesiter is in my runtime path? If I run echo $PATH, there isn't nvim-treesitter.

**Comment by theHamsta** [comment]
I think you can show your runtime path via `:echo &rtp` but when nothing is installed this is probably not the problem. Is your plug-in directory writable? Can you try `:TSInstallSync`. In theory it can also to your `stdpath('data')` but only when the plug-in directory is read-only.

**Comment by jordisantamaria** [comment]
I found the problem, nvim-treesitter was installing stuff in a wrong path. So removed the folder where nvim-treesitter was installing everything and now It's installing It in the correct path.

**Comment by paulo-granthon** [comment]
> I found the problem, nvim-treesitter was installing stuff in a wrong path. So removed the folder where nvim-treesitter was installing everything and now It's installing It in the correct path.

then what's the path it was installing to?

**Comment by jordisantamaria** [comment]
wait it's 2 years ago, there is no way I remember it.

**Comment by pearl-omalishe** [comment]
For anyone who will be looking into sometime later:
I had the very same problem. 

Pre-history: I started playing around with nvim some time ago, experimenting with Packer plugin manager and different plugins, then abandoned it for a while. Just recently I tried once again with (what I thought) a fresh start - I have removed and installed nvim again with `$ brew uninstall` and `$ brew install`, ensured that nvim and tree-sitter are the most recent versions, started my config anew, with `lazy.nvim` as a plugin manager this time.

But the `:TSInstall` seemingly did nothing at all, although reporting successful installations. 

Turns out, there was a Packer leftover in `~/.local/share/nvim/site/pack` to where all the parsers were installed by `:TSInstall` for some reason. Once I have removed `~/.local/share/nvim/site`, parsers started to be installed to `~/.local/share/nvim/lazy/nvim-treesitter/parser` and recognized by nvim afterwards. 

Looks like nvim-treesitter has some internal priority or sequence of where to install the parsers

Hope it helps
