### ISSUE TITLE
tree-sitter-dart

### ISSUE THREAD

**Issue by shivahnshankar** [nvim-treesitter/nvim-treesitter#213]
**Language informations**

Hi
I believe treesitter implementation for Dartl is progressing quite rapidly and it "seems" to be in a pretty usable state. Repo here:
[https://github.com/UserNobody14/tree-sitter-dart](https://github.com/UserNobody14/tree-sitter-dart)
Is there anyway we this can be included at this early stage for testing?

**Comment by theHamsta** [comment]
Could you try out: #215 and tell whether the parser is serving you well?

**Comment by Akin909** [comment]
Woah this is super exciting thanks for picking this up so quickly. I (overeagerly) just tried it out on a project and it works quite well. It seems to be missing a lot of class related highlights though and dart is pretty heavy on the classes so in a file using a framework like flutter it's almost entirely white

*Tree sitter*
![dart-treesitter](https://user-images.githubusercontent.com/22454918/88193273-63ec8780-cc35-11ea-8654-01dc95f7e25d.png)
*Random old screen grab of vim syntax* (The vscode bit isn't relevant here just an old screen grab)
![dart-highlight](https://user-images.githubusercontent.com/22454918/88193586-bd54b680-cc35-11ea-98bb-0ce3711948db.png)

I think the classes and operators aren't highlighted as well as methods etc. Most of the class related highlighting comes up a lot in dart

**Comment by theHamsta** [comment]
I've never seen dart in my life, so I just copied some stuff from the upstream repo together. Feel free to improve the highlights by adding new queries. For nested languages, we need language injection support for neovim though.

**Comment by Akin909** [comment]
👍 I'll try and tinker with it and open a PR, this is already really great for standard dart. The flutter is native rather than nested so won't need anything special I don't think just highlights for classes, methods and operators

**Comment by TimWhiting** [comment]
I'm one of the contributors on the tree-sitter-dart repository. Definitely highlighting has not been a focus for us right now. We have been mostly focusing on getting the grammar to work properly for the newest dart syntax, including non-nullable types. There are some corner cases of the language grammar that aren't currently handled still (Very small chance of it appearing in user code). I can work on the highlighting queries a bit later on this week, but if any of you have time and want to work on it feel free to open a pull request.

**Comment by TimWhiting** [comment]
@Akin909 
I think some of the difficulty with the classes is that it is hard from a parser to tell what is a class and what is a function. You have to do more than just parsing for that - you have to analyze the code (especially where the new and const keywords aren't used). I'd have to look deeper at the grammar to see if the grammar currently distinguishes between the two in the calling / instantiating position. If so, it would be easy to add highlighting. If not (which is what I expect), it could get much harder. Possibly if we can figure out which ones are uppercased, we could just apply a blanket rule that Uppercased 'function calls' should be highlighted like classes. I'm not super familiar with the highlighting features of tree-sitter, but I can take a look at them later this week probably.

**Comment by Akin909** [comment]
> I think some of the difficulty with the classes is that it is hard from a parser to tell what is a class and what is a function (from the callsite).

@TimWhiting that makes sense I just tried the treesitter UI in tree-sitter-dart to have a look at the tree that is created and can see what you mean i.e. classes all come up as `identifier`s. I think uppercased function calls would be a good work around if needed since I think that would cover most cases, except this wouldn't translate to instances (not sure if that's necessary anyway).

I've also noticed that there's no way to distinguish methods calls and properties which also come up as identifiers. Although as these are prefixed with `.thing` are maybe easier to identify (I'm guessing, I'm not sure how that would be conveyed with treesitter).

I haven't worked with treesitter before but from what I can see languages like go that use structs and java which has classes seem to be able to determine which nodes are classes or class-like but I guess that might not be applicable here.

Some sort of indicator that certain things are classes would be super helpful since at the moment I don't think there is a way to highlight these. I'm currently just looking at adding operators, punctuation and a few keywords.

**Comment by theHamsta** [comment]
@Akin909 there's already some regex query's for naming conventions in the highlight queries. Also, we have plans to make highlighting more semantic in future. You can already ask this plugin for a definition. In future, we want to leverage this information also for highlight (e.g. distinguishing types from values and local from imported names and parameters).

**Comment by Akin909** [comment]
Ah I've just seen the example thanks @theHamsta, I actually think the regex in there isn't working very well, locally it seems to only catch one or 2 matches not sure why. I tried
 ```
((identifier) @type
 (#match? @type "^[A-Z][a-z]+(\?:[A-Z][a-z]+)*$"))
```
in the tree sitter UI which catches most of the classes in my test file but when I add it to `highlights.scm` in your PR only partially matches some of the classes (but still a lot more than are in the current regex).

Would be good to know definitively if we can't get a class identifier from the grammar since this seems like it's going to be a bit brittle no matter :sweat:

**Comment by theHamsta** [comment]
Most other parsers use 
```scheme
((namespace_identifier) @type
 (#match? @type "^[A-Z]"))
```
for types. The regexes are evaluated into vim regexes (very magic) so they might behave a bit weird (with escaped `\`, I've never fully understood vim regexes): https://github.com/neovim/neovim/blob/bd5f0e9695cb21c8b97f844ce21432ee8d06b7ed/runtime/lua/vim/treesitter.lua#L133

This causes some problems: https://github.com/neovim/neovim/issues/12595

**Comment by Akin909** [comment]
That works much better :100: 
![treesitter-regex-dart](https://user-images.githubusercontent.com/22454918/88233604-ded29400-cc6f-11ea-8056-557bd7bf5c35.png)

**Comment by theHamsta** [comment]
Are those underscored names members? You could add a highlight for them as well.

**Comment by Akin909** [comment]
They are I did a quick search and found
```
((identifier) @field
 (#match? @field "^_"))
```
Which I've added. I've got a few tweaks locally which I think improve the highlighting, operators keywords etc. Think there's still a bunch that could be added down the line with all of this stuff think it'd be a very good start I can make a PR later. My branch is based on yours in #215

**Comment by theHamsta** [comment]
```scheme
((identifier) @type
 (match? @type "^_?[A-Z]"))

((identifier) @field
 (match? @type "^_?[a-z]"))

; or 
(class_body
         (identifier) @field)
; or
((class_body
         (identifier) @field)
 (match? @field "^_[a-z]"))
```
It works like Lisp just enclose the query to the parens of the parent

**Comment by UserNobody14** [comment]
Hey, I'm the guy who first started the dart tree-sitter implementation.

To answer your question about why almost everything's an identifier, it's just because that's how it was in [the dart specification](https://spec.dart.dev/DartLangSpecDraft.pdf). That doesn't mean everything is undefined, it just places most of the emphasis on the hierarchy of labels above a  particular grammatical node. 
I'm not very knowledgable about the common practices of writing a grammar for syntax highlighting, so I mostly just stuck to the official specification.

I'd be happy to help in any way I can, as Tim said, just open a pull request or an issue.

If you're interested in how our grammar handles various situations, you can look in the 'test' folder of our repository, which has a lot of different dart code examples, alongside their grammatical output.

**Comment by Akin909** [comment]
@UserNobody14 thanks for the heads up :+1: , I had a very quick look through the grammar and it looks like a few things like `method_invocation` and `method_reference` are commented out at the moment as is `class_literal` (which I'm guessing would cover the cases we are currently using a regex for), `field_access` etc ([one example line](https://github.com/UserNobody14/tree-sitter-dart/blob/a50a2ccbf6a42ee2515d458291a63c43a2b8a86c/grammar.js#L1040)).

Other than that as you say there's quite a lot already defined. I'll have a look at the output for some of the tests. I can raise an issue on the grammar repo to discuss this more over there if you'd prefer. It could be there's already ways around these things that I'm just unfamiliar with.

**Comment by theHamsta** [comment]
@UserNobody14 as far as I had a looked the parsed syntax trees right now: the quality of the parsing results are pretty good :+1: . We should be able to find out all missing information by additional queries and analysis of the AST.
