### ISSUE TITLE
`TSInstall`/`TSUpdate` could keep parsers' git repository 

### ISSUE THREAD

**Issue by younger-1** [nvim-treesitter/nvim-treesitter#2537]
**Is your feature request related to a problem? Please describe.**
I notice running `TSUpdate` the parsers' git repository will be clone to `stdpath('data')`. After updating parsers, therse repository will be deleted.

No really a problem, but I really wish `TSInstall`/`TSUpdate` could save these repositories to somewhere like `stdpath('data')/treesitter-parsers`. Some benefits:
1. It may save time to update parsers by avoiding clone them again. 
2. It is easier to rolling back to any git commit of nvim-treesitter and then install parsers for any reason
3. It is convenient to browser the source code of installed parsers
4. It can ease the burden of weird bugs causing by network problem of users from Mainland China

Sincere thanks for your work

**Comment by theHamsta** [comment]
Are you using Windows? At the moment we don't use git at all. We. Used to but now it's only a fallback. Not using git also has advantages:

- (initial) downloads are much faster since we're able to only fetch the latest commit. With git you can do this only for branches or tags
- you don't have to keep all the enormous git repositories which are usually big because the generated parsers are checked into the git repo and almost change every commit while being huge
- you can go to every commit with curl. With git you can only reach arbitrary commits when you do a full checkout and that commit is reachable in the history of one of the branches while checked

We could add an option to not delete the git repos. Please note that someone with a similar problem requested a feature to use a proxy/mirror of GitHub that was easier to reach from their country.

**Comment by younger-1** [comment]
Yes, I'm using windows. I just checked some parsers' repo for big files and found their `src/parser.c` file are usually big. Is this file generated? I agree with you that a proxy/mirror of GitHub is more suitable.

**Comment by younger-1** [comment]
I found a interface to fetch url for linux/windows which implemented by @williamboman in his [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer). These may be helpful 😃 
https://github.com/williamboman/nvim-lsp-installer/blob/fd417d0b2c35c12706b92ee6037c0223ebf77f07/lua/nvim-lsp-installer/installers/shell.lua and https://github.com/williamboman/nvim-lsp-installer/blob/fd417d0b2c35c12706b92ee6037c0223ebf77f07/lua/nvim-lsp-installer/core/fetch.lua

**Comment by theHamsta** [comment]
This feature is not planned. Git is not out main distribution mechanism. The repos don't scale well with the generated parser.c checked in. We don't want to leave garbage on the machine of our users.

I would love to switch back to curl even on Windows
