### ISSUE TITLE
Better control over conceals and highlighting

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter#2825]
Currently, conceals are set unconditionally, which is a regression over legacy syntax files which usually gate the more controversial ones (like JSON quotes) behind a global configuration option.

We should also add a way of enabling/disabling individual conceals; at the same time, we should _not_ replicate the zoo of language-specific `g:foo`globals. One possible idea is to use the now supported atom-style fallbacks for the conceal capture (`@conceal.fancy`, `@conceal.quotes`, or somesuch) to define levels of conceals which can then be selected by a predicate (which would have to be configurable; no idea yet how to do this with queries).

An alternative would be to define the conceals in separate queries that are optionally loaded, but that would likely have performance implications (and require additional query handling functionality).

**Comment by clason** [comment]
Come to think of it, this is an even larger issue: a not small number of Vim syntax files use global options to control highlighting (at the syntax level). To achieve parity, we need some way of influencing the queries from the Neovim side.

**Comment by theHamsta** [comment]
> Come to think of it, this is an even larger issue: a not small number of Vim syntax files use global variables to control highlighting (at the syntax level). To achieve parity, we need some way of influencing the queries from the Neovim side.

I don't see a need for that. A better way to select the queries (e.g. to filter out queries). We can already do conditional queries based on predicates. I used them in external repos when we wanted to make certain queries configurable.

Please don't add them to the highlights.

**Comment by clason** [comment]
I'm sorry, I don't get this. Are you saying we should _not_ make highlights configurable (in some way)?

**Comment by theHamsta** [comment]
> Are you saying we should not make highlights configurable (in some way)?

yes. It's far more easy to just let users make the changes they need for their queries than to explain and maintain switches. When captures are specific enough every capture in the queries can be turned to a no-op.

I would love to give more options to edit queries in a general way but I wouldn't add some predefined choices (on/off) into the queries.

**Comment by clason** [comment]
I think we're talking past each other here (any maybe should take it to the nvim-treesitter chat): I do _not_ want to add a bunch of configuration options; I thought I made this clear.

On the other hand, we _should_ make it easy for users to configure the queries; if that's already possible and just needs to be documented, so much the better. Can you give an example how that would look?

**Comment by theHamsta** [comment]
also just rather leave away something that could be controversial.

**Comment by clason** [comment]
Yeah, but then other people will request it (witness JSON quotes conceal). You can't make both happy without offering choice.

**Comment by theHamsta** [comment]
But also conceal just needs the on/off choice and it's rather a different module that you can turn off/on Highlights can already be deactivated by remapping the capture or remapping the highlight group. This is not possible with conceal yet. I'd just add a directive to add concealment which doesn't complicate any queries. Either `(conceal!)` or `(conceal! 2)` where number specifies the fanciness of the conceals.

Which might be just conceal isn't a real window option but rather a buffer one. Sure you could want to view the same file concealed and not concealed at the same time.

**Comment by clason** [comment]
But legacy syntax lets you _opt-in_ to individual conceals. I believe we need the same level of granularity to offer a full alternative.

**Comment by theHamsta** [comment]
We can give every conceal a level and name. Then you can refer to it in a similar way as to the highlight.

`(conceal! 2 "quotes")` the highlight modules could then have per language options either in terms of "fanciness" or individual features on/off. It would not be more verbose than the current solution

**Comment by megalithic** [comment]
With the latest changes to `markdown` and `markdown_inline`; will `@conceal` continue to be supported?

**Comment by pteroctopus** [comment]
I reported the problem here: https://github.com/nvim-treesitter/nvim-treesitter/issues/3723 and the issue was closed by @clason as a duplicate.

This issue is not solved for the last four months.

Also set conceallevel=0 doesn't work when used in .vimrc. Only if entered in command mode mannualy.

**Comment by skylarmb** [comment]
I have been struggling with this ever since starting to use TreeSitter, and have been watching this thread for a while. Today I stumbled across an interesting finding that I hope can help others who find this thread after googling concealment issues.

While troubleshooting this issue I noticed that my `conceallevel` was not what I specified in my `.vimrc`, where I explicitly set `set conceallevel=0`. Somehow `:set conceallevel?` was showing `2` in every file, even if I put the `set` as the very last line of my config file, indicating to me it was being overwritten after load by some plugin. Sure enough `set conceallevel=0` _after_ opening a JSON or markdown file solved all my woes with concealment.

[This thread led me](https://vi.stackexchange.com/questions/7258/how-do-i-prevent-vim-from-hiding-symbols-in-markdown-and-json) to discover that the VERY popular `Yggdroot/indentLine` plugin seems like the culprit here, and that disabling the plugin on relevant file types fixes the issue. 

**Fix option 1: Disable `indentLine`** 
```vimrc
let g:indentLine_fileTypeExclude = ['json','markdown']
```
However, completely disabling the plugin is a poor experience. There is an option to only un-conceal text around your cursor line when insert mode:

```vimrc
let g:indentLine_concealcursor = 'nc'
```
There is a different, nicer solution depending on your preferences that is more general to any filetype, which is to just use an `autocmd` to set conceal on enter/exit of insert mode. This keeps the pretty formatting unless in insert mode, which is a plus for me personally.

```vimrc
autocmd InsertEnter * set conceallevel=0
autocmd InsertLeave * set conceallevel=2
```

**Comment by lukas-reineke** [comment]
This is a bit off-topic from the issue here, sorry.

@skylarmb if you are using Neovim, and want indentation guides without conceal and all the mess you describe, you can use
https://github.com/lukas-reineke/indent-blankline.nvim

**Comment by dgmora** [comment]
What would be the way to disable certain conceals for some languages? I've searched different issues and documentation and can find an example on how to configure that. I imagine it's possible, but with my level of understanding of treesitter looks rather difficult.

At the moment what I just set conceal entering/leaving some languages, but it isn't ideal:

```
vim.api.nvim_create_autocmd({ "BufEnter", "BufWinEnter" }, {
  pattern = { "*.md", "*.json" },
  callback = function()
    vim.cmd("set conceallevel=0")
  end,
})

vim.api.nvim_create_autocmd({ "BufLeave", "BufWinLeave" }, {
  pattern = { "*.md", "*.json" },
  callback = function()
    vim.cmd("set conceallevel=3")
  end,
})
```

**Comment by aiotter** [comment]
I have been suffering from this issue for a long time.

I'd like to set `conceallevel=1` so that the concealed characters is replaced with a single space.
This is really nice because I can avoid seeing obstacle characters, and the line length is still the same with the original text.
However, some treesitter modules including markdown just removes the character instead of replacing them with the characters of the same length.

Currently there is no way to avoid this. I wonder this have to be fixed on neovim side.

**Comment by sisrfeng** [comment]
>  line length is still the same with the original text.
I need this feature too!
I use https://github.com/junegunn/vim-easy-align a lot, and usually set conceallevel as `2` and concealcursor as `n`.  The alignment is not so pretty if the concealed text is longer than 1 character.

**Comment by fspv** [comment]
Thanks @skylarmb this was exactly my issue! Spent more than a year looking for this answer. Maybe worth including that in the readme here then?

**Comment by emmanueltouzery** [comment]
one use-case that I have for this is that I wrote myself conceal rules for typescript to hide types.
I'd use it only in rare cases, on-demand toggle, just to temporarily drop the types and view the plain "javascript" code.

That works great, however it broke LSP hover popups, because they show markdown with conceal to hide the markdown markup. Because it sets the conceal, it also activates my typescript types conceal that I didn't intend to enable in this case.

So yes, ideally I'd love to able to create a specific @conceal.mine that i would activate manually and independently of the "general" conceal.

Right now in my case I'll comment out my conceal rules, I don't see any alternative :(

**Comment by clason** [comment]
Note that highlighting and conceals are completely controlled by Neovim now. I proposed "conditional" captures but that was rejected because it increased divergence from other editors, and being able to share queries is a goal with higher priority.

In any case, I am closing this because this issue is now out of scope for this repository.

**Comment by clason** [comment]
(There is an upstream issue on allowing `set_query` to extend rather than replace loaded queries; I believe this would allow you to solve your use-case.)
