### ISSUE TITLE
Not sure what's happening but a single `self` keyword in Python is not highlighted / correctly colored

### ISSUE THREAD

**Issue by nyngwang** [nvim-treesitter/nvim-treesitter#2946]
As title. I'm running my neovim setup on Ubuntu 20.04LTS, neovim at the latest version when I'm writing this. I'm at work so please forgive me for not reporting this using the template. I think this would have low-priority because it seems that it rarely happens. I'm sure this is not related to colorscheme because I have tested all treesitter-enabled ones that I have installed. To be specific: it's at the line containing `self.train_accuracy.result()` in the pic.

<img src="https://user-images.githubusercontent.com/24765272/169175147-275611b1-eebc-4b00-b83e-9b9526790634.png" width="600">

**Comment by theHamsta** [comment]
Please follow the issue template and provide plane text source code in addition to your screenshot

**Comment by nyngwang** [comment]
> Please follow the issue template and provide plane text source code in addition to your screenshot. [...]

Sorry I can't. It's not public code. If you don't know how to solve it you can close it.

> [...] Apparently the training accuracy of the parser is not 100% yet

I don't know what you meant.

**Comment by theHamsta** [comment]
You can try to debug it. The issue templates gives a few hints what you can try, including checking the highlight group that tree-sitter has set and the parse result of the parser. For the highlighting, there is the parser project, nvim-treesitter and Neovim involved. It can fail at any of the stages. This is why it is important to check whether the parser parsed correctly, and whether the highlight was determined correctly. If I remember correctly there are still limits set for the queries, so it's possible that one match just got lost due to query limits.

**Comment by nyngwang** [comment]
>  [..] If I remember correctly there are still limits set for the queries, so it's possible that one match just got lost due to query limits.

This is reasonable to me. Thanks for your explanation but I don't know how to debug so closing it for now.
