### ISSUE TITLE
def's names containing "def" part are highlighted like def in Clojure

### ISSUE THREAD

**Issue by Liverm0r** [nvim-treesitter/nvim-treesitter#3200]
### Describe the bug

https://user-images.githubusercontent.com/14236531/178567443-f73327a3-6633-4ee9-ad67-f81c10eaacc5.mov

Initially created here https://github.com/sogaiu/tree-sitter-clojure/issues/24

### To Reproduce

`:TSInstall clojure`;

write:
`(def default 1)`

### Expected behavior

`default` should be colored as any other variable

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
$ nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
```

**Comment by kyazdani42** [comment]
seems like it's caused by the line 108 in the clojure query:
```scheme
((sym_lit) @keyword
 (#lua-match? @keyword "^def.*$"))
```
I'm not sure why this is matched this way
@sogaiu would you know if we can remove this query ?

**Comment by sogaiu** [comment]
@kyazdani42 As I understand it, this file has been extensively modified by folks others than me since the initial version and I haven't really followed the changes.

Possibly people involved in this commit https://github.com/nvim-treesitter/nvim-treesitter/commit/1099809d706c2661440386330a13efbb66a8e927 might know better?

For reference, folks listed as contributors to `highlights.scm` appear to include:

* @Akeboshiwind 
* @theHamsta 
* @lewis6991 
* @Joakker 
* @dundargoc 
* @p00f

**Comment by p00f** [comment]
Someone might have wanted to capture all the "defining" keywords in one go (def, defn, defn-, defmacro etc). I think the solution is to handle capture keywords individually

**Comment by Akeboshiwind** [comment]
Hmm, it's been a while since I've thought about this.
But from what I remember this was intentional because there are a variety of symbols that are prefixed with `def`, some libraries define their own which I wanted highlighted (although compojure is the only one I can remember with `defroutes`).

That said, this is still a bug. Maybe we can swap it out for:
```scm
((sym_lit) @keyword
 (#any-of? @keyword
  "def" "defonce" "defrecord" "defmacro" "definline"
  "defmulti" "defmethod" "defstruct" "defprotocol"
  "deftype"))
```

We'd have to do the same for here too:
https://github.com/nvim-treesitter/nvim-treesitter/blob/0e29e2c6e16bba7b5267148c394f0c908f1ff43f/queries/clojure/highlights.scm#L285-R286

**Comment by Akeboshiwind** [comment]
Exactly @p00f

**Comment by Akeboshiwind** [comment]
I've opened a PR to fix this, I'm not 100% certain this is the perfect fix so feel free to comment with ideas :)
