### ISSUE TITLE
Provide an option to shallow clone parser repo

### ISSUE THREAD

**Issue by Neur1n** [nvim-treesitter/nvim-treesitter#3636]
**Is your feature request related to a problem? Please describe.**
Calling `:TSInstall` could result in slow downloading of the target parser in a big size repo.

**Describe the solution you'd like**
Provide an option to shallow clone the target parser, e.g. running `git clone --depth=1 ...`.

**Describe alternatives you've considered**
Not sure.

**Additional context**
N/A

**Comment by theHamsta** [comment]
@Neur1n are you on Windows? `:TSInstall` prefers curl over git. Specifically to avoid all those problems with git and specially with shallow commits.

We can't use `--depth=1` because it works only for trees like branches not for all isolated commits that we use in the lock files. There were long issues in the past to find a good solution to this but in the end we found that `curl`ing a specific commit-archive was faster.

The blocker for using `curl`+`tar` on Windows are symbolic links. `tar` will fail once it extracts a tar-ball with symbolic links (tree-sitter-typescript, tree-sitter-caml`). This is why git is still used on Windows. If you have the developer option enabled that non-admins can create symbolic links on Windows or if you're not using typescript/ocaml you can set that option to `false` https://github.com/theHamsta/nvim-treesitter/blob/7400a56adfea1441b0b5e0eeb40053b97dbe394d/lua/nvim-treesitter/install.lua#L15, e.g. `require 'nvim-treesitter.install`.prefer_git = false`.

That said `curl` is the preferred option. It is much faster than git anyway and only downloads shallow. We could go even more shallow by only downloading `parser.c`/`scanner.c` for the parsers that only need those two files. But that would be a different issue.

**Comment by theHamsta** [comment]
An idea to make it even faster would be to pipe the output of curl into tar which would avoid an intermediate file and allow to run the two processes in parallel.

**Comment by Neur1n** [comment]
@Neur1n Yes I'm on Windows. Thanks for the instructions!

**Comment by theHamsta** [comment]
I extended the Windows wiki: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#how-will-the-parser-be-downloaded
