### ISSUE TITLE
Replace julia grammar (temporarily)

### ISSUE THREAD

**Issue by savq** [nvim-treesitter/nvim-treesitter#3735]
Following https://github.com/tree-sitter/tree-sitter-julia/pull/54 and #3609, I've kept adding improvements to other parts of the Julia grammar. I'd like to see those changes applied sooner considering:

- Most Julia users would want to get a better grammar soon
- User feedback and bug reports make it easier to improve the grammar faster

Since this is a win-win, I propose we use my fork: [savq/tree-sitter-julia](https://github.com/savq/tree-sitter-julia) while we wait for the changes to be upstreamed. I'd also add myself as co-mantainer.

Thoughts? @theHamsta @mroavi @clason

**Comment by clason** [comment]
Not sure about this; switching parsers comes with friction, so I prefer not to do this temporarily. You can always replace the parser manually in your config, which should be the better approach for testing purposes.

That being said, I'm not against switching the parser for good if you commit to maintaining it? You could also try to have the Julia org adopt your fork; I'm sure they have more reason for rapidly improving the parser...

**Comment by mroavi** [comment]
I think this is a good idea. The state of the current parser is poor anyway. Many of the open issues (which date really far back) completely break the highlighting for entire files. As far as I know, very few people are using it in the Julia community. The grammar is something out of my scope that I haven't been able to contribute to. I think it would be great to capitalize on the great work that @savq has been doing.

**Comment by clason** [comment]
My point is:
* The "official" tree-sitter-julia parser is poorly maintained (not really the priority of anybody involved); I don't expect this to change anytime soon.
* There's precedent in switching parsers in nvim-treesitter to a better maintained one.
* This means that the new parser should come with a certain commitment towards maintenance.
* This means that a personal fork is not ideal (but, again, not without precedence).

Possible ways forward:
1. Either of you asks Max to add you as co-maintainer for the official parser.
2. You turn your fork into a "semi-official" one (maybe under a new org) and maybe add @mroavi as maintainer, too, just to have a better bus factor.
3. We can host the parser under the nvim-treesitter org (not my first choice, since we're not really in the business of managing parsers on top of queries).

The benefit of 2 or 3 is that you could also host the "source of truth" for the queries; this guarantees that parser and queries are always in sync (via tests), and makes it easier for me to fix breaking automated lockfile updates.

**Comment by savq** [comment]
> Not sure about this; switching parsers comes with friction, so I prefer not to do this temporarily.

By temporarily I mean that we'd use my fork while the changes are upstreamed. If for some reason upstream diverges —it accepts other PRs, but not the ones I've sent— then we can assume the change would be permanent.


> That being said, I'm not against switching the parser for good if you commit to maintaining it? You could also try to have the Julia org adopt your fork; I'm sure they have more reason for rapidly improving the parser...

Currently, my work on the parser is sponsored. And the goal is to have a complete parser by the end of the year. We haven't discussed having a repo in a different organization, since I expect the changes to be upstreamed eventually.

> You ask Max to add you as co-maintainer for the official parser.

Ok, I'll do that first.

**Comment by clason** [comment]
> Currently, my work on the parser is sponsored.

Who is sponsoring this, if I may ask? Would the sponsor be interested in hosting the parser?

Let me be blunt: Based on what I've seen, my expectation is not that these changes will be upstreamed in a timely manner, and if they do, it will be followed by another long period of inactivity where bugs and fixes just accumulate.

Hence I don't consider the parsers under the `tree-sitter` org as "official" in any way; they're just there to have some parsers for the library to "play with". The org lacks any vested interest in the languages themselves, which makes them poor stewards. So I'd vastly prefer a parser that is (really) maintained elsewhere.

Of course, if the upstream parser adds a motivated maintainer (you ;)), then this changes.

**Comment by savq** [comment]
I emailed Max and he's agreed to have me as co-maintainer.

> Who is sponsoring this, if I may ask? Would the sponsor be interested in hosting the parser?

Julia (via numfocus). It's more of a student stipend, like a second (smaller) google summer of code.

**Comment by clason** [comment]
> I emailed Max and he's agreed to have me as co-maintainer.

That's great! I'm very happy that the official grammar has a dedicated maintainer now. 

> Julia (via numfocus). It's more of a student stipend, like a second (smaller) google summer of code.

Nice! That's a very good idea.
