### ISSUE TITLE
Upcoming change to tree-sitter-clojure

### ISSUE THREAD

**Issue by dannyfreeman** [nvim-treesitter/nvim-treesitter#3998]
I'm opening this issue to let the maintainers know that we're going to be merging a change to tree-sitter-clojure master branch that might affect this repository.

The change is here: https://github.com/sogaiu/tree-sitter-clojure/pull/31

A brief overview of the changes:
`kwd_lit` and `sym_lit` will now contain up to 3 new nodes:

```
(kwd_lit
  ns: (kwd_ns)
  delimiter: "/"
  name: (kwd_name))
```

```
(sym_lit
  ns: (sym_ns)
  delimiter: "/"
  name: (sym_name))
```

Only the `(kwd_name)` and `(sym_name)` are required.
`sym_lit` nodes can still contain metadata nodes (this is unchanged).

Queries directly capturing `kwd_lit` or `sym_lit` should remain unaffected, so we're hoping this change is relatively backwards compatible. It should open up the door for easier highlighting of namespace and name parts of symbols and keywords. 

We'll be creating an issue in tree-sitter-clojure where we can post announcements ahead of time that anyone interested can subscribe to. I'll post a link here when we get that up. Please let me know if you have any questions.

If you are not prepared to use these changes, or they end up breaking something, there should be a tag `0.0.9` on the tree-sitter-clojure repo that will work.

**Comment by clason** [comment]
I see that you are providing queries in the repo; that makes things much easier. 

@sogaiu (listed as maintainer for the queries here; if this is incorrect, let us know!)

**Comment by clason** [comment]
Ah, I suspected something like that; this list was recently touched up.

**Comment by clason** [comment]
Do _you_ want to help maintain the queries here (he asked, hopefully)?

**Comment by clason** [comment]
Worth a try :D

In that case, I doubly appreciate you taking the time and opening the heads-up issue here!

**Comment by NoahTheDuke** [comment]
Thanks for the tag, I am interested and have tried to add queries in the past.

**Comment by clason** [comment]
> Thanks for the tag, I am interested and have tried to add queries in the past.

Great; you could follow the upstream PR and adapt the queries here when it is merged, and change the listed maintainer to yourself while you're at it!

**Comment by sogaiu** [comment]
As mentioned by @dannyfreeman above:

> We'll be creating an issue in tree-sitter-clojure where we can post announcements ahead of time that anyone interested can subscribe to. 

[Here](https://github.com/sogaiu/tree-sitter-clojure/issues/33) it is.

@NoahTheDuke Please consider subscribing to the announcement issue :)

(Of course, other folks are welcome to subscribe too!)

**Comment by sogaiu** [comment]
@NoahTheDuke 

I tried out @dannyfreeman's https://github.com/sogaiu/tree-sitter-clojure/pull/31 with a relatively recent neovim + nvim-treesitter.

It looks ok -- but this was a very brief test.

Here's how a portion of Clojure's `core.clj` looked with [the playground](https://github.com/nvim-treesitter/playground) on the left and the source file on the right:

![nvim-treesitter-playground-pr-31](https://user-images.githubusercontent.com/33044872/210520462-90304c91-75cd-4bea-90a5-1a288d89cb5d.gif)

Near the beginning of the video, it should be possible to see https://github.com/sogaiu/tree-sitter-clojure/issues/21 addressed.  The symbol name part of `^:static conj`, i.e. `conj` should be "reachable" via a `sym_name`, whereas before, for reasons (TM), it couldn't be picked out.

Near the point where the video loops, it should be possible to see `clojure.lang.RT/conj` recognized into a namespace piece -- `sym_ns` -- and a name piece -- `sym_name`.  This is what should make https://github.com/sogaiu/tree-sitter-clojure/issues/28 addressable via queries.

**Comment by amaanq** [comment]
Can this be closed? Mentioned change was merged so I'm guessing it's ok here too

**Comment by sogaiu** [comment]
AFAICT, only one new commit related to highlighting of Clojure has been created since this issue came about -- https://github.com/nvim-treesitter/nvim-treesitter/commit/4612212c72a3fe683cbca2f99977ad63b942f70e -- and that one looks like it's just related to typos, so I presume the queries have not been updated to make use of the change that was made to the grammar.

I don't know if @NoahTheDuke or others were using this to track adjustments to the highlighting queries and/or change in maintainer.

May be it's worth asking?

**Comment by NoahTheDuke** [comment]
lol I'm watching all activity in the repo cuz I'm curious and interested, so you don't have to keep this open for me.

**Comment by sogaiu** [comment]
@dannyfreeman May be this issue can be closed then?

**Comment by clason** [comment]
I don't think it's feasible to leave open tracking issues for every language, so I'm closing this. Going forward, I think the best way of handling changes like this is

1. open a draft(!) PR updating the queries to the upcoming change (so that we can just merge it when the change lands)
2. for massive rewrites that are bound to break a lot of downstream, add a comment to the "breaking changes" issue.
(Small breaking changes like a renamed capture don't have to be announced or mentioned; this is part of the expectation for using this repo.)

**Comment by amaanq** [comment]
> lol I'm watching all activity in the repo cuz I'm curious and interested, so you don't have to keep this open for me.

#4382, let me know what you think of the changes to Clojure there please :)

**Comment by sogaiu** [comment]
> Great; you could follow the upstream PR and adapt the queries here when it is merged, and change the listed maintainer to yourself while you're at it!

I think @NoahTheDuke has made some contributions since this discussion:

* [refactor: update Clojure queries](https://github.com/nvim-treesitter/nvim-treesitter/commit/ab3fb2a285e55a56b732d2f9f40ba7c3a10b87fc)
* [feat(clojure): add update-keys & update-vals](https://github.com/nvim-treesitter/nvim-treesitter/commit/7be9ebd06abe2ed836abd3e91acb0b243ddcafba)
* [fix(clojure): fix field highlighting](https://github.com/nvim-treesitter/nvim-treesitter/commit/e942c720acf44c5c19338ffd57185e9e0e027227)

Perhaps it makes sense to have him listed as the maintainer now?

**Comment by clason** [comment]
If he's volunteering to keep maintaining the queries here (i.e., consents to being pinged on every issue and PR that touches the queries).

**Comment by NoahTheDuke** [comment]
I can do that. Thanks for the tag, @sogaiu.

**Comment by clason** [comment]
Then just make a PR changing the `maintainer` entry in `parsers.lua` :)

**Comment by NoahTheDuke** [comment]
Oh cool, will do.

**Comment by sogaiu** [comment]
How about the repository `README.md`?

**Comment by clason** [comment]
That part is automated (and already taken care of).
