### ISSUE TITLE
[PHP highlight] autoindent turned off?

### ISSUE THREAD

**Issue by tobiwild** [nvim-treesitter/nvim-treesitter#462]
When I open a PHP file, setting `autoindent` is turned off. Is this intended?

I can provide more info if this is not reproducible.

**Comment by vigoux** [comment]
Reproducible on my side, and `verbose set autoindent?` says it has been set for the last time in the `php.vim` ftplugin.
Sounds like it does not come from us,

**Comment by stsewd** [comment]
Maybe related to https://www.reddit.com/r/neovim/comments/iv4w2l/neovim_suddenly_doesnt_indent_line/

**Comment by bigsweater** [comment]
The default PHP indentation plugin sets an `indentexpr`, [which overrides the `smartindent` setting](https://neovim.io/doc/user/options.html#'indentexpr'). (The plugin also [manually disables `autoindent`](https://github.com/2072/PHP-Indenting-for-VIm/blob/master/indent/php.vim#L524-L533).)  

This might be the `GetPhpIndent` function breaking since it relies on specific syntax plugins to work?

https://github.com/2072/PHP-Indenting-for-VIm/blob/master/indent/php.vim#L20-L23

As a workaround, I created a `~/.vim/after/indent/php.vim` file with the following contents:

```
setlocal indentexpr =
setlocal autoindent
setlocal smartindent
```

This will load after the indent plugin.

The default smartindent isn't as good as what the plugin does, but it's better than nothing.

**Comment by theHamsta** [comment]
@tobiwild can we close this as unrelated to this plugin?

**Comment by tobiwild** [comment]
Yes, I'm fine, thanks.

**Comment by przepompownia** [comment]
@here who interested let's look at the example from #2873 especially for any regressions, that (in intention) disables nvim-treesitter on phpdoc comments and on not recognized areas (e.g. unclosed coments, recognized as `error`s from treesitter perspective) only.
