### ISSUE TITLE
Install queries with `TSInstall` command

### ISSUE THREAD

**Issue by rusnasonov** [nvim-treesitter/nvim-treesitter#4677]
**Is your feature request related to a problem? Please describe.**
I am writing a custom tree-sitter grammar with syntax highlighting support. I don't understand why the TSInstall command installs the parser, but doesn't copy the queries for highlighting?

**Describe the solution you'd like**
Copy all queries from `queries` folder to rtp, when `TSInstall some-custom-grammar` called

**Comment by amaanq** [comment]
A lot of grammars don't have local queries to begin with, so this would be flaky at best and have hidden behavior for anyone testing out local grammars.

**Comment by lucario387** [comment]
That is doing a few assumptions:
- Do the queries conforming to nvim's queries? (Probably yes in this case, but what if the queries were written for Helix? for Zed?)
- Do the queries accurately follow the newest syntax? Probably not as well
- Do the queries "make sense" for neovim? Just because it's the author's intended syntax, that doesn't mean it's the 100% correct one, and doesn't need modifications

**Comment by rusnasonov** [comment]
Thanks for answer!

**Comment by theHamsta** [comment]
We had that idea for some nvim affiliated parsers like viml,vimhelp or maintainers that mainly wrote their parser for nvim. Would be open to auto-install or auto-import for selected parsers when the update-parser job is running.
