### ISSUE TITLE
[RFC] how to highlight ternary operator (? : )

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#470]
**Describe the bug**
`C` uses `@conditional` for the ternary operator, while Java/JS use `@operator`. We should find a common policy for all the languages.

**Expected behavior**
C, JS and Java agree on a common policy for the operator.

I have a preference for `@operator` since all other `@conditional` are keywords.

EDIT: adding C#, Dart to the languages with ternary operator.

**Comment by kyazdani42** [comment]
well i agree `@operator` sound good for a question mark in a ternary, but in some languages (like javascript), question mark can also be an operator, or in rust. So `@conditional` would be more appropriate for a ternary imo.

**Comment by TravonteD** [comment]
+1 for using `@conditional` as operator tends to not be strongly highlighted, and usually we want conditionals to stand out.

**Comment by bluz71** [comment]
I agree with @theHamsta that highlight consistency between languages for the same concept is highly desirable.

The Treesitter team could literally choose either `@conditional` or `@operator` and consider it correct, since it both an operator (it is called Ternary *Operator* after all) AND it is a conditional (since it a shortcut for logic statements).

With my Vim themes `@operator` would look better. So in an informal poll I choose `@operator`.
But I am fine with `@conditional` as well.

Whichever is chosen should be used in C, C++, JavaScript Rust, Python, Java, Ruby etc etc (all languages that support the ternary operator.

**Comment by p00f** [comment]
I chose `operator` because `:` is already an operator (in "enhanced for-loop") so i just had to add `?`

**Comment by vigoux** [comment]
I think we resolved that RFC ? @theHamsta can you confirm ?

**Comment by theHamsta** [comment]
It is resolved when there is a PR unifying the highlighting.

**Comment by vigoux** [comment]
Following the conversation, we'll use `@conditional`, I'll open a PR right now.

**Comment by vigoux** [comment]
After looking at the queries, it seems that everything is in order already, can we close that then ?

**Comment by theHamsta** [comment]
It's not implemented for Java/JS/Rust/Dart

**Comment by vigoux** [comment]
Then I'd say it's the responsibility of language maintainers, I don't know Java or JS that much, and the ternary operator in Rust (the `:` is for type indications).

**Comment by theHamsta** [comment]
Adding C# to that list.

**Comment by vigoux** [comment]
That's a todo for language maintainers, let's ping them here
