### ISSUE TITLE
Relationship with LSP (especially coc.nvim)

### ISSUE THREAD

**Issue by nomasprime** [nvim-treesitter/nvim-treesitter#484]
I've used nvim-lsp, now [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), but ran into an [issue with TS](https://github.com/neovim/nvim-lspconfig/issues/250).

In this issue Justin comments on [the general direction of LSP](https://github.com/neovim/nvim-lspconfig/issues/250#issuecomment-683455159). This is essentially the same direction as [coc.nvim](https://github.com/neoclide/coc.nvim).

I'd dismissed coc.nvim in the past as not being very Vim-like but neither is LSP and as coc.nvim seems to be better aligned with the current direction of LSP I decided to give it a go, at least until nvim-lspconfig is comparable and stable. I actually thought these two projects could collaborate but that [doesn't look likely](https://github.com/neoclide/coc-tsserver/issues/204).

So far I'm really impressed with coc.nvim: it's really easy to configure; great, if sometimes brief, support; and everything, pretty much, works really well.

I was looking at improving my spellchecking setup today which eventually lead me to [vigoux/LanguageTool.nvim](https://github.com/vigoux/LanguageTool.nvim) and then I discovered [Tree Sitter](https://github.com/tree-sitter/tree-sitter) and this project.

I watched the [talk](https://www.youtube.com/watch?v=Jes3bD6P0To) where Max mentions the relationship between Tree Sitter with LSP. However, maybe since then the amount of overlap between the two technologies has increased:

1. The description of functionality within the [refactor section](https://github.com/nvim-treesitter/nvim-treesitter#refactor-highlight-definitions) of this project's readme is very LSP-like, even mention's LSP fallbacks
2. There is an [LSP proposal for semantic syntax highlighting](https://github.com/microsoft/language-server-protocol/issues/18)

I still need to experiment with Tree Sitter but it would be really helpful to get some advice and other perspectives in the meantime:

1. How do you think the relationship's changed since the talk?
2. Should the two technologies coexist and, if so, what's the best approach to integrating them?
3. Does anyone have any experience or can point me in the right direction to configuring the fallbacks with coc.nvim?

PS Longer description than I'd initially intended because I needed to get my thoughts in order. Decided to keep it in case anyone on a similar journey finds it useful.

**Comment by nomasprime** [comment]
Hi @vigoux, discovered your work today. Really nice.

**Comment by kyazdani42** [comment]
basically, lsp gives much more accurate informations about a project, its types and relationships between modules.
Treesitter works on a file. Although it could be used on multiple files to create advanced relationships, this is not its primary goal.
Treesitter still aims at giving the best highlighting experience, with very low latency, which would not be the case for lsp.
I use both projects and they have their own goal. Treesitter gives the ability to have very efficient highlighting, when lsp gives me the informations i need for my projet.
One could argue lsp is not needed as its not vim like, but hey, its 2020 and productivity is the key here.

**Comment by vigoux** [comment]
So, that will take some time to answer, as there is many good questions in here.

First, I feel blessed that you came through all of this journey, and came to us here today, thanks for reaching out !

First, I want to draw your attention to the difference between LSP and Treesitter.

- Treesitter
  - A library : meaning you can bundle it fairly easily (as long as you load the parsers correctly), and it is just a C function call away
  - Made for parsing files : meaning all the information you will get will come from that one file (but you can still do some searches through it)
  - Incrementally : this is meant to parse really really fast, while initila parsing will go as usal, incremental parsing will go fast
  - With error recovery : that is worth a book, but that's what makes tree-sitter awesome, any syntax error will not mess up the highlighting of the whole file
  - Open-source : we can fork it, and just maintain it ourselves, there has already been some PRs from us
- LSP
  - A protocol : you implement the protocol on both ends (editor, and language) and it "just" works, but at the cost of roundtrips between LSP client and server
  - made for managing projects : across multiple files then, so that needs indexing, etc etc, and it takes some time
  - Made for VSCode : and the spec follows what VSCode needs, and what MS wants

So, both of them can compete, but _LSP gathers accurate information slowly, while Tree-sitter gathers (fairly good) approximations really fast_.

Finally answering your question

1. I don't think it changed _that_ much,  though, LSP has grown big, and tree-sitter is just adding new parsers left and right. One thing to note though is that _anyone_ (really) can add a TS parser, while implementing a full Language Server will for sure take you some time.
2. That will not be a surprise if I say that they should, because they have different scopes, LSP for project-wide requests, TS for file-wide requests. One thing though is that I really think that we can build a generic LSP implementation built on top of tree-sitter, where you just need to add your parser, a few queries, and it is good to go.
3. A bit more technical heh, fallbacks use the builtin LSP implementation, and I don't use CoC.nvim so I can't help here.

As a conclusion, and that will not surprise anyone, I am a heavy Tree-sitter user, and I also use LSP a lot when working on neovim. And I think that we miss the point by comparing TS and LSP, TS will be used within nvim to reimplement old mechanisms like syntax highlighting, and ftplugins (think about multi-language documents using different LSPs depending on the position in the file), and I really think that we should think of this as an interaction between TS and LSP. TS will do the dispatch, as it is generic, fast, and lightweight; and LSP will do the heavy-lifting, as it is accurate but specialized and slow.

PS: Thanks for the kind words !

**Comment by nomasprime** [comment]
Thanks @kyazdani42. Good to meet someone that's been on a similar journey.

> productivity is the key here

Couldn't agree more. These newer technologies have definitely given a huge boost to the community. As always, it takes time for them to stabilise and become fully utilised.

Do you use coc.nvim or nvim-lspconfig now and why?

**Comment by steelsojka** [comment]
I'll add a note on the refactor modules as well. Even though "Go to definition" and rename in treesitter isn't nearly as powerful as an LSP. We only know the syntax tree for single file, not an entire project. But they are much faster and lighter weight than a full blown LSP. I use a lot of the features along with an LSP (especially highlighting usages and definitions)

**Comment by nomasprime** [comment]
@vigoux wow, thanks for such a complete and in-depth reply.

My initial instinct was that TS would help boost more traditional file-based operations while LSP is more geared towards project-wide. Thanks for giving me confidence in this approach.

I'm going to start by disabling duplicated languages in sheerun/vim-polyglot and replacing with TS.

I'll experiment with the overlapping file-level operations and report back; have an open references highlighting issue with one of the LSPs so hoping TS will be a better solution at the file-level overall.

Thanks @steelsojka for the additional insight regarding the refactor modules. Not sure how I'm going to do this yet but I guess this are will require the most wiring because of the overlap.

Generally excited by the possibilities of TS and various plug-ins, eg, [architext.nvim](https://github.com/vigoux/architext.nvim), look really interesting.

**Comment by vigoux** [comment]
Thanks man! Architext was also meant to show how easy it is to hack things on with treesitter.

An advise : find an idea, and hack this on, it will be awesome I am sure!

**Comment by kyazdani42** [comment]
@nomasprime i used to use coc.nvim as a lsp, but now i use nvim lsp because i have more control over it, and its builtin. I like to hack on things these days so nvim lsp is a better choice, but coc.nvim works fine otherwise.

**Comment by nomasprime** [comment]
@vigoux sure, like contributing.

@kyazdani42 was working on that too but TypeScript support's an issue. Will think about going back when the project becomes stable.

**Comment by theHamsta** [comment]
LSP and tree-sitter overlap. After all it was the approach of Microsoft and Github of a IDE-fication of their editors (now everything is owned by Microsoft).

They have strategies: tree-sitter abstracts over all languages and gives the editor a syntax tree which it can use for cross-language logic for folding/highlighting/semantic highlighting. LSP is more about externalising the logic for each language. The editor has far less control on what exactly should should happen. Both protocols  are used  by Microsoft and Github for indexing format and go-to definition provider for large repos.

It's nice to have both in Neovim. For tree-sitter you almost pay nothing for having it running and you don't have install a languages server and since a lot of logic happens in the editor you can hack and fine-tune it with plugins. You have full control what's going on. If LSP offers a feature it might be superior because it can specialize in the actual languages.

Example semantic highlighting: LSP highlighting for Java/C++ might be more precise with an actual compiler in the background but you have to wait for it to load and the logic doesn't run on every keystroke (due to remote protocol) and tree-sitter can work even if your code can't compile yet when build files are still missing. An the "can be more precise" is only correct if someone wrote the server and the feature for this.

Smart rename with LSP is great when your server supports Cross-File rename. But I had often the situation that server couldn't rename for some reason (maybe a syntax error in the file) and only some servers support it. Our smart_rename does the change instantly and works for almost all languages. It's only suited for very local renames. Thinking of python-language-server: the rename is slow and rarely works. Thinking of Java LSP: it will really rename every occurrence in every file.

So if you want to script your logic or run low level stuff on every keystroke: use tree-sitter. if you want the best pre-defined solution for a high-level task: LSP. Having an editor that has both will offer you smart features for all languages and environments.

**Comment by yatli** [comment]
My 5 cents on this:

tree-sitter hackable != LSP out of control. I enjoy writing language servers and don't see it a daunting task.
They're just different things. tree-sitter is a parser. For the LSP tasks to work you'll often need more than a parser. Likewise, for syntax highlighting/folding/structural editing etc. , LSP is not going to be that helpful (at the moment, at least -- they're still trying to standardize the semantic highlight endpoint, and it's not designed to throw back structured code at the editor).

tree-sitter should replace the syntax files in nvim, while LSP shouldn't.
Suppose I'm to edit some huge json streams. The first thing I'll do after firing up the editor is `:syntax off` because it's too slow. I can barely move the cursor with that on.
Now tree-sitter should solve that problem.
LSP-wise? No. I mean, should the editor has spare cpu cycles, do it, asynchronously. I'm fine with it checking for schema compliance in the background. But not in my synchronous screen-brain-keyboard loop.

I'd be very happy if language server implementations start to use tree-sitter powered parsers though!

**Comment by vigoux** [comment]
I _really_ think we can implement an lsp using only treesitter, and I think it can be faster than some lsps....

**Comment by kyazdani42** [comment]
lsp could use treesitter as a parser for the base analysis of the code too :)

**Comment by vigoux** [comment]
I was thinking of something like locals, includes and so on.
The nice thing would be that this LSP would be language agnostic.

And the language agnostic-ness of this LSP can question the actual need of lsp even...

**Comment by nomasprime** [comment]
Very clear now and integration with LSP seems fairly straightforward, [Polyglot](https://github.com/sheerun/vim-polyglot) is something else but I'll open a separate issue for that.

Thanks for all your help.
