### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-treesitter/nvim-treesitter#714]
**Describe the bug**
I'm trying to install it for the first time and it gives em this error:

```
Error detected while processing /home/hrq/.vim/plugged/nvim-treesitter/plugin/nvim-treesitter.vim:
line   12:
E5105: Error while calling lua chunk: ...hrq/.vim/plugged/nvim-treesitter/lua/nvim-treesitter.lua:2: attempt to index field 'fn' (a nil value)
Press ENTER or type command to continue
```

**Output of `nvim --version`**
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.4/build/config -I/builddir/neovim-0.4.4/src -I/usr/include -I/builddir/neovim-0.4.4/build/src/nvim/auto -I/builddir/neovim-0.4.4/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
We require the newest nightly versions of Neovim.

**Comment by hrqmonteiro** [comment]
> 
> 
> We require the newest nightly versions of Neovim. It will not work with 0.4.4
> 
> @vigoux we now know that we must not use vim.fn in the your version is too old message.

Just installed nightly and the same error appeared.

**Comment by RaulAlejandroSalas** [comment]
Just installed nightly and the same error appeared.

> > We require the newest nightly versions of Neovim. It will not work with 0.4.4
> > @vigoux we now know that we must not use vim.fn in the your version is too old message.
> 
> Just installed nightly and the same error appeared.

me too

**Comment by theHamsta** [comment]
![image](https://user-images.githubusercontent.com/7189118/100465650-f911f800-30cf-11eb-9612-9e505b2631cd.png)

The build bot has given up building the nightly from source since 16 days. The newest version of this plugin requires a nightly not older than four days. You either have to build it from source or downgrade this plugin to before the commit cited below.

There was a hard change in the tree-sitter API: https://github.com/nvim-treesitter/nvim-treesitter/commit/90d6ef96d2930b8efe2ece2c231b31df6c3ff7c3

**Comment by f0s3** [comment]
@theHamsta after manually cloning the treesitter repo and `git reset --hard fccc159` (one commit before `90d6ef9`) still gives me the same error. Anything I missed?

Just decided to use it for the first time and it gives me an unpleasant feelings of instability from the beginning. Hoping it is not always like so and I just happened to be in the "right" place in the "right" time.

Hoping for your soon reply

**Comment by p00f** [comment]
if you cloned it anyway, why not build the latest version?

**Comment by steelsojka** [comment]
@f0s3 If you go one commit before the breaking change then it won't work. There's changes in neovim and in this repo. Use the latest commit of this repo and neovim master.

You are opting to use alpha level software so API breaking changes should be expected. We want to get the API right before 0.5 drops and we can't make larger changes anymore.

**Comment by MadRafa** [comment]
I've been trying to install this plugin several times for the last 3 months, it ALWAYS gives the same error of needing a newer version of neovim even though I have the nightly version and I'm always downloading the latest version. Good to know that I'm not the only one with this issue.

**Comment by steelsojka** [comment]
@MadRafa the best way to avoid any errors is to build the latest from source. Nightly builds aren't happening right now and are behind.

**Comment by f0s3** [comment]
I m not sure but it seems that I already use the latest master of this repo and the master of neovim (not nightly). I use arch btw. https://www.archlinux.org/packages/community/x86_64/neovim/
What am I doing wrong? It doesn't work whatever I try. 
Output of `nvim -v`:
```
NVIM v0.4.4
Build type: Release
```
and the plugin is latest master (cloned manually in the plugins folder instead of vim-plug (for me to be able to go to different commits and test if this works)). But even using vim-plug doesn't give me any behavior change. It still just doesn't work.

Let me know if you see I do something wrong. Btw, what is the reason of building neovim manually from source? I didn't try it yet (because I think there is no difference from what my package manager does and I want as much of the programs to be updated by package manager instead of keeping them up-to-date manually), but is it the thing I need to do?
I think as it is an issue that many people face with, we should raise it a bit. For now the project is unusable.

**Comment by p00f** [comment]
@f0s3 master of neovim is `0.5.0 - gxxxxxxxxx`. You need to install neovim-git from the AUR. I don't understand how you compiled v0.4.4 from source

**Comment by f0s3** [comment]
Yes, I have just come up to the same solution by myself trying out different neovims available on aur.
So for the reference and for all of those who are on arch:
`pacman -S neovim-git`
remove treesitter folder and do `:PlugClean` and `:PlugInstall`
And reopen nvim.

This solved it for me!

**Comment by p00f** [comment]
>  remove treesitter folder and do :PlugClean and :PlugInstall

You didn't need to remove the plugin.

**Comment by theHamsta** [comment]
FYI: https://github.com/neovim/neovim/releases (new releases)
