### ISSUE TITLE
Add Markdown parser

### ISSUE THREAD

**Issue by b3nj5m1n** [nvim-treesitter/nvim-treesitter#872]
**Language information**

There is a Markdown parser for treesitter: https://github.com/ikatyang/tree-sitter-markdown

As I understand it, this was already in this repository, but has been removed due to #602. Afaik, this issue has been resolved about a week ago, see https://github.com/ikatyang/tree-sitter-markdown/pull/17, so I would assume that it can be added back in as a default parser, right?

**Comment by theHamsta** [comment]
I tried it maybe three weeks ago and still had segfaults. I can try it for one week to check whether any issues arrise. Fuzzer results look good so far.

**Comment by b3nj5m1n** [comment]
@theHamsta Personally I've been using it for about a week without issues, but I understand you don't want to put it in if tests fail.

I'll keep this issue open until a Markdown parser gets added.

**Comment by theHamsta** [comment]
I guess we can include it if it causes no problems. It's just intolerable for a highlight plugin to crash the whole editor and since it mainly happened with LSP hover windows it could happen in any moment. So we need to be absolutely sure that no crashes happen in practice.

**Comment by theHamsta** [comment]
@vigoux you did also do some research on the Markdown parser. Any opinions on this issue?

**Comment by tami5** [comment]
Few days ago, I uncommitted 265, and so far everything seem to work, no issues whats so ever.

**Comment by vigoux** [comment]
Thanks for the report and inded there was some progress lately.
I am going to start a fuzzing campaign on the markdown parser, and my policy is : any crash or hang makes it a no no.

**Comment by vigoux** [comment]
Got two crashes, so here again that's a no no...

Sorry for the time it takes to add the markdown parser. The issue we have is that this parser is written mostly in C, which (as it turns out), is fairly tricky.

If one want to reproduce, here are the two chrashing inputs I found : [faults.tar.gz](https://github.com/nvim-treesitter/nvim-treesitter/files/5865433/faults.tar.gz)

**Comment by theHamsta** [comment]
Day 2 of the test week. Crashed my Neovim when opening hover window for Python.

**Comment by b3nj5m1n** [comment]
I've now also experienced an issue while writing pandoc Markdown, caused by a fenced code block of latex in the YAML metadata section.

It's definitely not ready to be officially supported, I'll keep this issue open to track progress on this or any other Markdown parser being added.

**Comment by ikatyang** [comment]
> Would still prefer if someone could write an actual tree-sitter parser for markdown and not just an interface to handwritten scanner rules.

As far as I know, it's not possible to parse Markdown with the so-called actual tree-sitter parser due to the fallback mechanism in Markdown, e.g., `[` may or may not be a link start, which requires backtracking and tree-sitter does not support it. For reference, there is also a tree-sitter-like parsing system whose [official markdown grammar](https://github.com/lezer-parser/markdown) is also written by hand due to the reason mentioned above.

> It's just intolerable for a highlight plugin to crash the whole editor

Sorry for the inconvenience, the crashes I've seen so far are mostly caused by my assertions, which can be handled but the result tree will probably be truncated from the character that triggers the assertion failure, is it acceptable?

**Comment by theHamsta** [comment]
@ikatyang doesn't tree-sitter support backtracking by declaring `conflicts`? I know how much effort you put into your parser and I think that we can get it to state where it can be used without terminating vim.

Regarding the assertions, we could try compiling with assertions disabled. Do you think that this could solve the issue? The tree-sitter parser should pass fuzzing tests without crashing. It's ok if the parsing result is wrong in some ill-formed cases.

**Comment by ikatyang** [comment]
> @ikatyang doesn't tree-sitter support backtracking by declaring conflicts?

Tree-sitter only forks the tree whenever there is ambiguity, i.e., SHIFT/REDUCE or REDUCE/REDUCE conflicts, it in fact does not backtrack, but it can be seen as parser-level backtracking somehow, what I meant above is the lexer-level backtracking. It may(?) be possible to use parser-level backtracking to simulate lexer-level backtracking but it means that basically it'll fork the tree whenever it encounters a character since there is too many possibilities for the Markdown language, so I simply did not take this approach into my consideration.

> we could try compiling with assertions disabled. Do you think that this could solve the issue?

Those assertions are the expectations for the latter code so I cannot even tell what will happen since it's undefined behavior.

> It's ok if the parsing result is wrong in some ill-formed cases.

I've opened https://github.com/ikatyang/tree-sitter-markdown/issues/24 to track it.

**Comment by resolritter** [comment]
@ikatyang in this topic of "forking", one thing you can try is having a **external** "marker rule" (not an official name, just what I call them) which looks far ahead and does not insert a node into the tree. I'm sure you know it but, by default, rules prefixed with `_` are not shown in the tree, thus you should be able to abuse this mechanism as much as you want without cluttering the output.

One relevant application of this is the automatic semicolon insertion for JS and TS. In that case, the semicolon rule might positioned at some arbitrary point in the tree *before* the semicolon *would* appear, then the scanner checks far ahead of the current position to decide if it actually appeared or not.

To that point, in order to decide between two rules by looking farther into the code without consuming tokens, you could try doing something like the following

```
option_1: ($) => (
   seq($._option_1_marker, $._actual_option_1)
),

option_2: ($) => (
   seq($._option_2_marker, $._actual_option_2)
),

rule: ($) => choice(
    $.option_1,
    $.option_2
)
```

On the external scanner, you say `lexer->mark_end(lexer);` at the start of those "marker nodes" (relevant for avoiding consuming the tokens) and scan forward as much as you want, then return `true` if they were a match indeed.

As a possible inspiration, there's [this recent PR](https://github.com/tree-sitter/tree-sitter-typescript/pull/126/commits/0440dd53709cda43ac1c0299cc57ac80cdcbfbc2) where I had the `_function_signature_semicolon_before_annotation` and `_function_signature_semicolon_after_annotation` rules appear before the actual semicolon. Then @maxbrunsfeld refactored the logic and unified it with the existing `AUTOMATIC_SEMICOLON` code path. He can give better advice on this practice and/or correct me if the above doesn't make sense. You can also check out the [TS scanner](https://github.com/tree-sitter/tree-sitter-typescript/blob/master/common/scanner.h#L73) or the [JS scanner](https://github.com/tree-sitter/tree-sitter-javascript/blob/6296f902ca511bf601cb13f5c9f548fc1a540425/src/scanner.c#L76) for more examples.

Finally, please don't get discouraged if it doesn't work out this way; I think your parser is great and it being a "hand-written parser underneath" is not a problem per se - I noticed there are a ton of tests and it seems to cover pretty much the whole spec. If that's what you need to do in order to achieve a more complete result, then I'm all for it. It's possible that it's just  missing some reasonable `ERROR` nodes on a few ill-formed cases and/or more fuzzying.

**Comment by tami5** [comment]
@vigoux I think tree-sitter markdown might be ready to be enable, it would be awesome if you give it another test

**Comment by theHamsta** [comment]
@tami5  if you want to try https://github.com/nvim-treesitter/nvim-treesitter/pull/1202

**Comment by paniash** [comment]
Hi! Is this still open? A rough estimate when it will be merged with tree-sitter?

**Comment by theHamsta** [comment]
Probably not so soon. A crashing parser is not tollerable for interactive in-process use in a editor.

**Comment by MDeiml** [comment]
I started writing my own tree-sitter markdown parser at <https://github.com/MDeiml/tree-sitter-markdown> (also based on the [Github flavored markdown spec](https://github.github.com/gfm/)) to try and make something more "tree-sitter friendly". My plan is to use the external scanner as little as possible which means probably using it to parse block structure and code span and emphasis delimiters.

I don't yet know if this is going to work. Markdown is a really difficult language to parse, even the official spec recommends to do [at least 2 passes](https://github.github.com/gfm/#appendix-a-parsing-strategy) which would obviously be against tree-sitters constraints. But I will keep this thread updated.

**Comment by alemuller** [comment]
@MDeiml, if you need any help with in tree-sitter, get in touch.

I became quite good at writing parsers. Despite having only pushed a couple to github, I've more than 20 parsers (just counted, had no ideia it was so many) in various degrees of completion (mostly from small languages, thought). 

I usually get bored writing from the language I was working with, and switch to a new one, and I end up never finishing them. I don't push them to github because I worry that I might stop others from implementing because they think someone else already did.

Probably should create a `tree-sitter-dump` repo.

I'm currently working on a `*printf` string format parser to highlight the conversion specifiers and escapes. I think this one will get finished. Had to learn js to generate the rules for this one...

**Comment by MDeiml** [comment]
@alemuller thanks. Maybe I'll take you up on that. Also thanks to all the positive reactions. I honestly didn't expect so many people waiting for this :)

**Comment by clason** [comment]
(Let me know if you would like a `nvim-treesitter` Matrix channel to coordinate -- I know the "official" chat room for nvim-treesitter is on Zulip, but I have the worry that this has a too high bar for some...)

**Comment by theHamsta** [comment]
Doesn't the gitter channel allow to use matrix? I think even Zulip can be used with a matrix account.

**Comment by clason** [comment]
You can indeed access the Gitter room from Matrix; if you prefer, I can add this to the Neovim space.

(I don't believe you can access Zulip from Matrix without setting up a bridge -- I seem to remember somebody working on it but I don't think it's very far along yet.)

**Comment by clason** [comment]
(Gitter is pretty much dead these days.)

**Comment by theHamsta** [comment]
We could also create a separate room for matrix. We should ask @vigoux as he set up all the communication around this project.

**Comment by clason** [comment]
So any Gitter room is transparently bridged to Matrix (since Matrix acquired Gitter); it's just the frontend that's not receiving any love anymore. That means we can just re-use that room, and you get the Zulip bridge for free (for as long as that's working). I've added this to the Neovim space (together with a number of other plugins).

We can discuss setting up a more general "Neovim tree-sitter" space (for general, including upstream Neovim, discussions) along the lines of https://matrix.to/#/#neovim-guis:matrix.org, too; although maybe there is no need for that.

(In general, I'd suggest anyone still using Gitter to move to Element; not only is the frontend _much_ nicer, you'll also get a lot more Neovim rooms that are Matrix native -- most core devs hang out (only) there, and I'd love to see more treesitter devs, too ;))

**Comment by vigoux** [comment]
Adding my two cents to this: I think that at some point we will need to move away from gitter, mainly because this is kind of deprecated now.
Bridging zulip and matrix should not be more difficult than bridging gitter, so I think this is a reasonably good time to make the switch.

I'll dig into setting up the bridge the a newly created nvim-treesitter channel.

The question of space vs channel, is orthogonal IMO, but I think we should avoid "dispersing" things, and having only a channel is nice.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by clason** [comment]
> I'll dig into setting up the bridge the a newly created nvim-treesitter channel.

Note that this is _not_ a new channel; I've just added the old Gitter channel (which internally was converted to a Matrix room on a different homeserver after the acquisition). From Element, you won't really notice a difference (for now). But I'd be happy to set up a new room, if you prefer.

And Spaces are just a way to bundle rooms (== channels); you can join them and immediately get a list of related channels you can join; the point is increasing visibility. But you can also ignore them and just join the room itself.

**Comment by vigoux** [comment]
Then I'd say that if we don't have to do anything to make the move, we're happy ;-)

In any case, I'll move the bridge to use Matrix instead of Gitter, just to be sure we are using a "recent" protocol.

Thanks for the time you took to make that @clason !

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by clason** [comment]
Just to make it clear then: The main question was whether we want to have a general "all things tree-sitter around Neovim" discussion channel (including parser development, Neovim core API etc.) instead of or in addition to the `nvim-treesitter` _plugin_ discussion channel?

**Comment by vigoux** [comment]
I would go to the "all things tree-sitter and Neovim" direction.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MDeiml** [comment]
My initial implementation is done. You can try it, but it is still very experimental and I know at least of some examples that do not get parsed properly (see https://github.com/MDeiml/tree-sitter-markdown/issues).

While I'm cleaning up my code and fixing some of these issues I would love some input on which nodes to include in the syntax tree. I decided to output only information that is relevant to highlighting, meaning I don't for example mark [soft line breaks](https://github.github.com/gfm/#soft-line-breaks) and I don't differentiate between [tight and loose lists](https://github.github.com/gfm/#loose).

I think there are also some plugins using https://github.com/ikatyang/tree-sitter-markdown which has quite a different output than my implementation. So insight into this from the plugin point of view would also be very helpful.

**Comment by clason** [comment]
FWIW, I would try to keep non-highlighting (editing) in mind from the beginning. Doesn't mean everything should be noded, but if it's something you could conceivably use in structural editing (selecting, replacing, moving), I'd err on the side of keeping it in.

**Comment by clason** [comment]
Oh, and there's now a "Neovim treesitter" Chat room: https://matrix.to/#/#nvim-treesitter:matrix.org

(This need not replace the nvim-treesitter _plugin_ chat room on Gitter; the `neovim-treesitter` name was just temporarily blocked.)

**Comment by theHamsta** [comment]
@MDeiml just tried your markdown parser and it feels actually quite mature. Can we include it as an experiemental parser instead of ikatyang/tree-sitter-markdown. Would be good to do the same fuzzing test that we did with ikatyang/tree-sitter-markdown

**Comment by MDeiml** [comment]
I would love that! Just haven't have time to work on this more in the last week, so I would still rate this as quite experimental.
