### ISSUE TITLE
Ruby Symbols are highlighted the same as Constants

### ISSUE THREAD

**Issue by semanticart** [nvim-treesitter/nvim-treesitter#874]
Thanks for the great project!

**Describe the bug**

Ruby Symbols are highlighted the same as Constants

**To Reproduce**
1. Create a ruby file with the content below
2. Note that the symbol keys are `TSConstant` as are actual constants.
3. Note that they're syntax highlighted the same

Example file
```
{
  symbol: Constant::ANOTHER_CONSTANT,
  foo: 1,
  bar: true,
  baz: 'a string'
}
```

![Screen Shot 2021-01-25 at 11 41 30 AM](https://user-images.githubusercontent.com/8633/105746178-1ff07d00-5f0d-11eb-94f2-af63735206a9.jpg)
![Screen Shot 2021-01-25 at 11 41 21 AM](https://user-images.githubusercontent.com/8633/105746181-21ba4080-5f0d-11eb-87a7-69dc1c0ba0f1.jpg)

**Expected behavior**
Symbols can be highlighted differently from constants.

**Additional context**
#864 is relevant. I can make this work locally by changing 

```
[
 (bare_symbol)
 (heredoc_beginning)
 (heredoc_end)
 (simple_symbol)
 (delimited_symbol)
 (hash_key_symbol)
 ] @constant
```

to

```
[
 (bare_symbol)
 (heredoc_beginning)
 (heredoc_end)
 ] @constant

[
 (simple_symbol)
 (delimited_symbol)
 (hash_key_symbol)
] @property
```

though I'm not strictly sure that `@property` is the necessarily the best analog here. I chose it because of its use in Javascript objects.

![Screen Shot 2021-01-25 at 1 00 28 PM](https://user-images.githubusercontent.com/8633/105746390-61812800-5f0d-11eb-9bea-e33dde947ea1.jpg)

**Comment by theHamsta** [comment]
@TravonteD

**Comment by theHamsta** [comment]
Could you make a PR from your proposal? I'm myself not a ruby user and just adapted the queries to the renamed node types. Probably, the previous query had a syntax error and did not even do anything.

@steelsojka is there anything that we can do about this query duplication, or is the official remedy: repair your rtp? Because it would not make take the pain to change it in my setup.

**Comment by semanticart** [comment]
@theHamsta happy to make a PR 👍  #875

**Comment by steelsojka** [comment]
@theHamsta Yeah I'm not sure... I submitted a PR when I first found it https://github.com/neovim/neovim/pull/13778 but I couldn't reproduce it on my other computer so I figured it was localized to my setup. I haven't had time to fix it on my other computer, so I haven't come up with anything yet. Are you using packer.nvim by chance?

**Comment by theHamsta** [comment]
yes, I use packer.

**Comment by steelsojka** [comment]
I'm using packer.nvim as well. I wonder if it's duplicating some rtp paths...

**Comment by bluz71** [comment]
Ruby symbols are not properties.

I just upgraded to the latest tree-sitter and immediately noticed this change. With my themes, [moonfly](https://github.com/bluz71/vim-moonfly-colors) and [nightfly](https://github.com/bluz71/vim-nightfly-guicolors), the result is less nice since instance variables and symbols are now highlighted in the same color. A similar problem the original poster had where symbols and constants were highlighted in the same color.

Previously Ruby symbols were highlighted as constants, which were pleasing with my themes, but in all honesty the original poster is correct, Ruby symbols are not constants, but they are even less like properties than constants in my opinion.

[This wikipedia page](https://en.wikipedia.org/wiki/Symbol_(programming)) on programming language symbols is interesting.

I would argue that a new `TSSymbol` / `@symbol` highlight group should be created for symbols (if that's possible). The good thing is that would **not** be Ruby specific since quite a few languages contain the concept for symbols (or atoms):

- Ruby symbols
- Dart symbol
- Elixir atom
- Erlang atom
- Julia symbol
- Scala symbol
- JavaScript ES6 Symbol

I will spawn a new request for this.

**Comment by bluz71** [comment]
New issue created #892, requests new `TSSymbol` / `@symbol` highlight group for languages that support symbols and atoms (e.g. Ruby, Elixir, Julia, Scala etc).

**Comment by semanticart** [comment]
> Ruby symbols are not properties.

This is true. If expanding the `TS` vocabulary to include `Symbol` is within scope, I'm all for this.

**Comment by bluz71** [comment]
@semanticart,

The Treesitter folks did include [namespaces](https://github.com/nvim-treesitter/nvim-treesitter/issues/516) and [tags](https://github.com/nvim-treesitter/nvim-treesitter/issues/465) at my request.

The logic is the same here with regard to symbols, that being a genuine programming language construct that spans multiple languages.

If there is enough Neovim Treeesitter man power then I would be quite confident that this request will be viewed favourably.

It would solve this issue for sure.

**Comment by bluz71** [comment]
A new `TSSymbol` highlight group has been implemented and merged.

By default it links to `Identifier` which is the same default as used by `TSProperty`. So for many Vim themes it should look the same as seen in this issue.

But for certain themes, such as my own, `TSSymbol` can be overriden.
