### ISSUE TITLE
Upstreaming queries

### ISSUE THREAD

**Issue by colinxs** [nvim-treesitter/nvim-treesitter#904]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Are the queries contained in this repo upstreamable? I'm still new to treesitter (but hoping to help with `tree-sitter-julia`, but it's my understanding that these queries _should_ be editor agnostic. I see there are some vim references in the `scm` files, so I'm not sure how feasible this is, but it would be nice to get any modifications upstreamed (especially for a repo like `tree-sitter-julia` which doesn't contain queries.

**Describe alternatives you've considered**

**Additional context**

**Comment by theHamsta** [comment]
tree-sitter proposes a few standard highlight groups and you can also use them in Neovim if you add them to the following dict.

```lua
local hlmap = vim.treesitter.highlighter.hl_map

-- nvim-treesitter Highlight Group Mappings
-- Note: Some highlight groups may not be applied upstream, some may be experimental

hlmap["annotation"] = "TSAnnotation"
```
At the moment tree-sitter-emacs and we maintain own queries simply because we can make them a bit more specific and map to Neovim specific groups. Also this achieves some inter-language consistency for a editor. This is not a must just happened to develop in this way (I originally wanted to just take the queries from the repos). It's usually no problem to get from our queries to the emacs ones or to the ones that are typically in the repo. They all just have a slightly own style. 

Regarding tree-sitter-julia, I don't think that any patch will be upstreamed so soon to this defacto inactive repo. We would be happy if you're interested in maintaining a fork. There are quite a few easy to fix issues with this parsers.

**Comment by colinxs** [comment]
Thanks for the prompt reply! Your reason for keeping the queries in nvim-treesitter makes sense. It sounds like there just isn't a good standard right now for what the queries should contain (NeoVim and Atom are the only editors I'm aware of that are really pushing for tree-sitter right now). Perhaps in the future it will be standardized in a way that allows for editor-agnostic queries (similar to how TextMate grammars are easily shared across editors).

As for tree-sitter-julia, you're right that it's been fairly inactive. I'm still getting acquainted with tree-sitter but hope to submit some PRs soon. You mentioned above:

> There are quite a few easy to fix issues with this parsers.

Do you have any particular suggestions in mind? Perhaps that would be a good place for me to start.

**Comment by stsewd** [comment]
I think we can close this issue, hopefully sharing queries can be done one day.
